<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_LOGOUT</name>
   <tag></tag>
   <elementGuidId>5203a6f4-f8e5-4cfa-9630-5b74f5ea1db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='j_idt11:j_idt25:j_idt177']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5047155-4aee-4b55-9092-d83205ea16ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>59f285f8-afc6-4855-8593-c532ec8c4a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>96a82d0b-a511-4e85-80a5-5bbacd7aed57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt11:j_idt25:j_idt177&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>b0e5c42b-562d-42a6-a11c-6c80d5b6dc6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='j_idt11:j_idt25:j_idt177']/span[2]</value>
      <webElementGuid>18037919-540e-4e8a-ae4f-921acb4c5851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Info'])[1]/following::span[3]</value>
      <webElementGuid>4a3da4af-250b-4626-93cf-d0dc70f663c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::span[5]</value>
      <webElementGuid>07729be0-9527-467e-a331-c8bfbeaae59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OP Receipts'])[2]/preceding::span[1]</value>
      <webElementGuid>5552e613-e4eb-4d88-aa90-ab8155405985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pharmacy POS'])[1]/preceding::span[1]</value>
      <webElementGuid>e368ac3f-1ee7-4df4-aadd-7538b967c3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGOUT']/parent::*</value>
      <webElementGuid>84a7aee4-2d6d-4cde-8dd3-3ecedeb1ddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span/button/span[2]</value>
      <webElementGuid>3dc9fe70-ed6d-423c-8efa-73f85df5e380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>4f0314dd-4d85-4759-ab6d-d9f157e9791a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
