<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGOUT</name>
   <tag></tag>
   <elementGuidId>66e7ea5c-1dbe-45b9-ae49-e74e2440241d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='j_idt11:j_idt25:j_idt154']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28a04cf2-d05d-4cdc-b0cc-ec74696f4e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt11:j_idt25:j_idt154</value>
      <webElementGuid>b5b71bdd-84e7-406c-9608-2696d9d332a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_idt11:j_idt25:j_idt154</value>
      <webElementGuid>b42f94ec-f9ba-446a-a897-5141d16ef998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left btnstyle ui-state-focus ui-state-hover</value>
      <webElementGuid>8e56e5bf-12ce-429d-970c-6c5995ab2b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;j_idt11:j_idt25:j_idt154&quot;});return false;</value>
      <webElementGuid>d2cd7553-668a-49d9-943f-0c2c7817b06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e03d75c4-92f2-4c9a-92f7-a4fb4bcddc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53a33358-25ad-4b9c-83ea-779fe329f3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17ed9883-a3ad-4405-85ae-871c33ba7d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>dad628c4-b944-4ab6-a683-7fc1e69c7454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt11:j_idt25:j_idt154&quot;)</value>
      <webElementGuid>98231be8-4b5b-4cbf-a24b-f4b8b55fd379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='j_idt11:j_idt25:j_idt154']</value>
      <webElementGuid>e4d22dcc-827c-4d0e-ac07-85db59027da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt11:j_idt25:menubar1']/ul/li/ul/li[5]/a/span/button</value>
      <webElementGuid>a06bcdfe-5953-4dfc-89a1-6d869f4390a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Info'])[1]/following::button[1]</value>
      <webElementGuid>c6aa77d9-2eca-4673-b25b-4ba65cc0d424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::button[2]</value>
      <webElementGuid>1c444bb3-5280-4191-8237-f9fb3a7ccd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OP Receipts'])[2]/preceding::button[1]</value>
      <webElementGuid>dcc182b6-8d87-483f-8284-081d5ae5e8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span/button</value>
      <webElementGuid>8d4e1070-5001-4b09-8f08-e6eab27d2ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'j_idt11:j_idt25:j_idt154' and @name = 'j_idt11:j_idt25:j_idt154' and @type = 'submit' and (text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>b27944b7-fcdf-47f5-953f-5323872c3579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
