<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Excisional debridement of skin and subc_699982</name>
   <tag></tag>
   <elementGuidId>0296b785-befc-4a91-827f-0b9f5943691c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='statusDialog_modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#statusDialog_modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e15c96ec-c2bf-4b6d-9e1e-a56201c6b52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusDialog_modal</value>
      <webElementGuid>cd49b5c4-1152-4573-8750-7dd36f20b97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-overlay ui-dialog-mask</value>
      <webElementGuid>ccacf721-86fb-4569-adc0-cb10ac281266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusDialog_modal&quot;)</value>
      <webElementGuid>bfb3e6e1-b57e-437e-9fa7-110faa8dafd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='statusDialog_modal']</value>
      <webElementGuid>0b6341c6-16e6-4a83-bcc7-ce7a8b22dfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[84]</value>
      <webElementGuid>d02a14d5-4705-4b24-917b-4718b0c5a7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'statusDialog_modal']</value>
      <webElementGuid>03ee8a66-fe17-4184-a8fb-99827835c3b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
