<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Service</name>
   <tag></tag>
   <elementGuidId>5a1e112b-0e28-4428-a297-7339c8071912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='AccumedHaadActivityListForm:j_idt1965']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e79c43c9-d217-4f9e-9214-54e49a1472ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:j_idt1965</value>
      <webElementGuid>ed0a43ca-7e44-464b-b154-d994e9e17c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:j_idt1965</value>
      <webElementGuid>e047441c-37bc-46ca-9a1d-295c907b5c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left ui-state-focus ui-state-hover</value>
      <webElementGuid>8f959c34-b85b-442e-a2a8-bb656a120f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.bcn(this,event,[function(event){this.disabled = true;this.className += ' ui-state-disabled ';},function(event){PrimeFaces.ab({s:&quot;AccumedHaadActivityListForm:j_idt1965&quot;,u:&quot;AccumedHaadActivityListForm:activityDisplay growl AccumedHaadActivityListForm:datalist&quot;,onco:function(xhr,status,args){PF('dataTableActivity').filter() ;handleComplete(xhr,status,args);;}});return false;}]);</value>
      <webElementGuid>ef8c69ca-c1a8-475d-afef-3e91856d9b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6163c57-a573-4f57-b5c6-f8a9f06265f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db4550e2-7668-4084-9523-47f229a4589c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8e0c5f9-1fd4-4480-aebf-79aac437815a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Service</value>
      <webElementGuid>e30a9ce1-7172-4347-b653-4e53f5a92402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:j_idt1965&quot;)</value>
      <webElementGuid>d2d99355-cf60-4cb7-9303-f8d001974903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='AccumedHaadActivityListForm:j_idt1965']</value>
      <webElementGuid>09b73ac4-286b-4047-a623-06eae6cef2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:activityDisplay']/table/tbody/tr[2]/td[12]/button</value>
      <webElementGuid>4469ebfc-b990-4524-9eaf-21744f5744f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Service'])[5]/following::button[1]</value>
      <webElementGuid>4463fe5a-ebcd-4a18-91b6-777dc6f00777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package'])[7]/following::button[1]</value>
      <webElementGuid>6373ac9a-690b-486f-95e9-3002cf5ea824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[12]/preceding::button[1]</value>
      <webElementGuid>a7e22709-90d4-4363-9477-58ad30ba0a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/form[2]/fieldset/div/span/table/tbody/tr[2]/td[12]/button</value>
      <webElementGuid>5ec3c480-062a-4497-a07a-04dd69ad16cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'AccumedHaadActivityListForm:j_idt1965' and @name = 'AccumedHaadActivityListForm:j_idt1965' and @type = 'submit' and (text() = 'Add Service' or . = 'Add Service')]</value>
      <webElementGuid>4669f43c-c521-454b-8518-7bd5006608de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
