<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomePatient Journey ManagementData Entry</name>
   <tag></tag>
   <elementGuidId>72e5f391-5679-493d-b560-895137c77971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainForm:j_idt183']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3da7de9c-c2c3-4059-a3c6-c5725a3cad6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainForm:j_idt183</value>
      <webElementGuid>96c3c7e4-7463-43f8-8b54-3cd20c379d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-breadcrumb ui-module ui-widget ui-widget-header ui-helper-clearfix ui-corner-all</value>
      <webElementGuid>1a31a12e-c892-43c7-b4c0-dc36ff160171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>967b80c2-5ac3-4f30-bc7c-b19e27a4be49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomePatient Journey ManagementData Entry</value>
      <webElementGuid>71586765-f179-4921-aff0-7bf81e93e66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainForm:j_idt183&quot;)</value>
      <webElementGuid>83709b7f-d6cc-4ef4-80d6-540013a7f7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mainForm:j_idt183']</value>
      <webElementGuid>04e114b9-e0ca-415b-91ca-e5d7ba728c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div</value>
      <webElementGuid>debd97da-b528-4a59-8f26-882f226ff653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGOUT'])[1]/following::div[3]</value>
      <webElementGuid>d09a54f0-c608-409e-bd1e-92c0b40fac89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Info'])[1]/following::div[3]</value>
      <webElementGuid>2d8b350e-774d-4ce1-b9c0-6e9f98ead9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>f8f3e6e3-8980-47bc-8012-33566395415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mainForm:j_idt183' and (text() = 'HomePatient Journey ManagementData Entry' or . = 'HomePatient Journey ManagementData Entry')]</value>
      <webElementGuid>070a65aa-7bf5-4cde-8ec1-b98f10a4e5f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
