<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomePatient Journey ManagementData Entr_90615c</name>
   <tag></tag>
   <elementGuidId>94607636-8766-4b62-bf46-3fafb6e14a65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='j_idt190']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#j_idt190 > div.ui-layout-unit-content.ui-widget-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53a92b71-9667-40ea-8961-fb6e53575d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-layout-unit-content ui-widget-content</value>
      <webElementGuid>de2554bb-cb76-480c-929d-65d824af9c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>


HomePatient Journey ManagementData Entryfocus = function() {PrimeFaces.ab({s:&quot;mainForm:j_idt192&quot;,f:&quot;mainForm&quot;,u:&quot;mainForm:facilityLicense&quot;,onco:function(xhr,status,args){checkChangeLicense();;},pa:arguments[0]});};$(function() {focus();});



$(function(){PrimeFaces.cw(&quot;Poll&quot;,&quot;checkModifiedChangedPoll&quot;,{id:&quot;phWLForm:checkModifiedChangedPoll&quot;,frequency:30000,autoStart:true,fn:function(){PrimeFaces.ab({s:&quot;phWLForm:checkModifiedChangedPoll&quot;,f:&quot;phWLForm&quot;,g:false});}});});onload = function() {PrimeFaces.ab({s:&quot;phWLForm:j_idt193&quot;,f:&quot;phWLForm&quot;,pa:arguments[0]});};$(function() {onload();});


Create New Visit Ammar

Search
Rerouted from Coding stage.








                                    Create New VisitExportui-button
                                    
                                    

                                       FP1NE Rows Per Page20304050607080
                                PatientFilter by PatientMRNFilter by MRNVisit NoFilter by Visit NoAdmission DateAdmission Date 
                                      
                                    Discharge DateDischarge Date 
                                      
                                    National IDFilter by National IDPhoneDepartment(DIABETES VIRTUAL INSULIN PUMP ) CLINIC--666??????? ??????? ???????????????? ????????A1C  PROJECT CLINICACCIDENT &amp; EMERGENCYADENO-TONSILLECTOMYADULT DIETITAN CLNIC MALEADULT INSULIN PUMP CLINICANESTHESIA CLINICANTI SMOKING CLINICAUDIOLOGY AND BALANCE CLINICAllergy/ImunologyyuyyyAnesthesia Clinic (AM)Anesthesia Clinic (PM)Artificial LimbsBABY COT WARD-BCBARIATRIC SURGERY CLINICBLOOD BANKBOARDING FAST TRACKBOARDING FEMALE MEDICALBOARDING MALE MEDICALBOARDING PEDIATRICBOARDING RESUS ROOMBOARDING TRAUMABUSINESS CENTERBusiness Trip Check upCARDIOLOGIST - CONSULTANTCARDIOLOGY CLINICCARDIOLOGY CLINIC - 2 AMCARDIOLOGY ECHOCARDIOGRAHPYCARDIOLOGY SCREENING CLINICCHILDHOOD DEVELOPMENTAL AND BEHAVIORAL DISORDERSCHILDHOOD DEVELOPMENTAL AND BEHAVIORAL DISORDERS 2CLINIC GALLSTONESCONSULTING PHARMACYCardiologyCardiology Clinic - 2 PMCardiothoracic SurgeryDANTAL-GPC CLINIC-5DAY SURGERY UNIT D1 DSUDCC PHARMACYDCC PHARMACY (1)DELIVERY ROOMDELIVERY ROOM-1DELIVERY ROOM-2DELIVERY ROOM-3DELIVERY ROOM-4DELIVERY ROOM-5DELIVERY ROOM-6DELIVERY ROOM-7DELIVERY ROOM-8DELIVERY ROOM-9DENTAL  CLINIC 9DENTAL CLINIC -PHC 1DENTAL CLINIC -PHC 2DENTAL CLINIC -PHC 2 (1)DENTAL CLINIC 1DENTAL CLINIC 10DENTAL CLINIC 11DENTAL CLINIC 2DENTAL CLINIC 3DENTAL CLINIC 4DENTAL CLINIC 5DENTAL CLINIC 6DENTAL CLINIC 7DENTAL CLINIC 8DENTAL CLINIC PHC 5DENTAL CLINIC PHC 6DENTAL HYGINE -12DERMA CLINIC VCDERMA FINGERPRINTDERMA(NAEL HATATAH) CLINICDERMATOLOGY (  LASER )DERMATOLOGY (DR.ALI) CLINICDERMATOLOGY (FEMALE RESIDENT)CLINICDERMATOLOGY 1DERMATOLOGY 2DERMATOLOGY CLINIC 3DERMATOLOGY PHC (PM)DERMATOLOGY PHC CLINICDERMATOLOGY PHC CLINIC - 2DERMATOLOGY VIRTUAL CLINIC-PMDEVELOPMENTAL AND BEHAVIORAL DISORDER CLINIC 2 DEVELOPMENTAL AND BEHAVIORAL DISORDERS ( screening)  PHC 2DEVELOPMENTAL PEDIATRIC VCDEXA SCANDIABATIC PITUTARY GLAND CLINICDIABETES  ENDOCRINE PEDIA &amp; ADOLESCNCE 2DIABETES  ENDOCRINE PEDIA-5DIABETES  FOLLOWUP CLINICDIABETES  FOLLOWUP CLINIC 1DIABETES  FOLLOWUP CLINIC 2DIABETES ANDROLOGY CLINICDIABETES BLOOD EXRTACTION (FEMALE)DIABETES BLOOD EXRTACTION (MALE)DIABETES CARDIOLOGY CLINIC-1DIABETES CARDIOLOGY CLINIC-2DIABETES CLINIC - 1DIABETES CLINIC - 10DIABETES CLINIC - 2DIABETES CLINIC - 6DIABETES CLINIC - 7DIABETES CLINIC - 8 (DR SALEH)DIABETES CLINIC - 9DIABETES CLINIC 4DIABETES CLINIC 5 (DR.SAEED)DIABETES CLINIC-3DIABETES COMPANY CLINICDIABETES DIETITIAN CLINICDIABETES EDUCATION CLINICDIABETES ENDOCARIONOLOGY PEDIA &amp; ADOLESCENEDIABETES ENDOCRINE PEDIA-3DIABETES ENDOCRINE SURGERYDIABETES ENDOCRINOLOGY - 6DIABETES ENDOCRINOLOGY -1DIABETES ENDOCRINOLOGY -3DIABETES ENDOCRINOLOGY 5DIABETES ENDOCRINOLOGY 5 (1)DIABETES ENDOCRINOLOGY 7DIABETES ENDOCRINOLOGY SCREENINGDIABETES ENDOCRINOLOGY-2DIABETES ENDOCRINOLOGY-4DIABETES FEMALE SCREENING CLINICDIABETES GESTATIONAL CLINICDIABETES INSULIN PUMP PEDIA &amp; ADOLESCENDIABETES INTENSIVE INSULIN THERAPY CLINICDIABETES MALE SCREENING CLINICDIABETES MULTI DISCIPLINARY CLINICDIABETES NEPHROLOGY CLINICDIABETES NEUROLOGY CLINICDIABETES NEUROLOGY CLINIC-2DIABETES OBESITY CLINICDIABETES OBESTARIC CLINICDIABETES OPTHALMOLOGY CLINICDIABETES OPTOMETRIC CLINICDIABETES ORAL HYGIENE CLINICDIABETES OSTEOPOROSIS CLINICDIABETES OSTEOPOROSIS CLINIC 2DIABETES PEDIA  &amp; ADOLESCENCE CLINIC 1DIABETES PEDIA &amp; ADOLESCENCE /SCREEINGDIABETES PEDIA CLINIC - 4DIABETES PEDIA DIETITIAN CLINICDIABETES PEDIA EDUCATOR CLINICDIABETES PEDIA SCREENINGDIABETES PHYSICAL EXERCISE CLINICDIABETES PRECONCEPTION COUNSELLINGDIABETES PRIMARY HEALTH CARE CLINICDIABETES PSYCHIATRY CLINICDIABETES PSYCHOLOGIST (2)DIABETES PSYCHOLOGIST(1)DIABETES REAFL RX (FEMALE)DIABETES SCREENING GASTATIONALDIABETES TRANSITIONAL CLINICDIABETES TYPES 1 CLINICDIABETES VIRTUAL  CLINICDIABETIC OBESITY CLINIC 2DIABETIC OSTEOPOROSIS FRACTURES CLINICDIABETIC PODIATRIC CLINIC -1 DIABETIC PODIATRIC CLINIC -2DIABETIC PODIATRIC CLINIC -3DIABETIC PODIATRIC CLINIC -4DIABETIC REFILLRL CLINICDIABETIES CLINIC 8DIALYSISDR FAISAL ALAQILI CHEST CLINICDYSLIPEDEMIA CLINICDentalDermaVenDevelopment and Behavior disorders ( screening) PHC Development and Behavior disorders ( screening) PHC 3Diabetic Dental Clinic -1Diabetic Dental Clinic -2DialysisECHO UNIT EMERGENCYEMPLOYEES CLINICENDOSCOPYENDOSCOPY (ENDO)ENDOSCOPY CLINICENDOSCOPY UNITENTENT (PRE OPERATION)ENT CLINIC - PHCENT CLINIC -1ENT CLINIC -2ENT CLINIC -3 ENT CLINIC VCER PHARMACYESWL CLINCEVALUATION HOME HEALTH CAREEmergencyEndocrinologyEndoscopy (END2)Endoscopy clinic-ERFIRST VISIT-PHCFOLLOWUP DEPARTMENTFURNITURE MAIN STOREFamily PracticeFive days programGALLSTONES CLINICGASTRO - 2GASTRO - CONSULTANTGASTRO - SPECIALISTGASTROENTEROLOGY CLINICGASTROENTROLOGY CLINIC (AM)GB STONES CLINIC PHC ONLYGENERAL SUREGERY CLINIC - 3GENERAL SUREGERY CLINIC -1GENERAL SUREGERY CLINIC -2GENERAL SUREGERY SPECIALISTGENERAL SUREGERY-PHCGENERAL SUREGERY-PHC 2GENERAL SUREGEY CLINC VCGENERAL SURGERY - 4GastroenterologyGastroentrology Clinic (pm)General Medical Check upGeneral PracticesGeneral SurgeryGeneral SurgeryGerontologyGynecologyHEMATOLOGY (GHUZAYEL)HEMATOLOGY ONCOLOGY CLINICHEMATOLOGY ONCOLOGY CLINIC 2 HEPATOBILIARYHEPATOLOGY CLINICHIGH RISK DIABETES CLINICHOSAM CLINICHOSPITAL DIRECTORHearing AidsHematologyHematology Oncology Clinic 3Hematology clinic 5HepatologyHome Health CareINFECTION CONTROLINFECTIOUS DISEASES CLINCINPATIENT PHARMACYINT MED SCREENING CLINIC-PHC 2INT MEDICIN ( DR JIHAN MAHMOUD ) CHEST CLINICINT MEDICIN ( RASHA )CLINICINT MEDICIN (DR ABDUL BASSET)CLINICINT MEDICIN (DR ADAWEYAH)CLINICINT MEDICIN (DR MOHAMAD RAMADAN)INT MEDICIN (DR MOHAMAD RAMADAN) CHEST CLINICINT MEDICIN (DR MOHAMAD SAFI)CLINICINT MEDICIN (KAMAL)CLINICINT MEDICIN CLINIC ( ALI ALQAHTANI )INT MEDICIN CLINIC ( WEAAM AHMED )INT MEDICIN VCINTENSIVE CARE UNIT -ICUINTERNAL  MEDICIN CLINIC (MESHAL ALENEZI )INTERNAL MEDICINEINTERNAL MEDICINE - CONSULTANTIndustrial Check upInfectious Disease CLINICInfectious DiseasesInpatientInternal MedicineIqama Issuance and  Renewal Check upKING SALMAN HOSPITALLABORATORY - DEPARTMENTLABORATORY MAIN STORELAUNDEYLEGAL AFFAIRSLIVE QUALITY MAIN STORE W HOUSEMAXILLOFACIAL SURGERYMEDICAL DIRECTORMEDICAL RECORDS DEPARTMENTSMEDICAL REPORTSMOH DIABATIC  CLINICMOH HOSPITAL - DBAMORTUARYMaternityMedical report clinicNEONATAL INTENSIVE CARE UNIT (NICU)NEPHROLOGY CLINICNEURO MEDICALNEURO SURGERY VCNEUROLOGY CLINICNEUROLOGY CLINIC VCNEUROSURGERY CLINIC (am)NURSING HOME HEALTH CARENUTRITION CLINICNeonatal-Perinatal MedicineNephrologyNeuro-SurgeryNeurologyNeurosurgery Clinic (pm)Non electronic wheel chairNuclear MedicineOB / GYNE CLINIC - 3OB GYNE CLINICOCCUPATIONAL THERAPYOPD BLOOD EXTRACTION-FEMALEOPD BLOOD EXTRACTION-MALEOPHTHALMOLOGY CLINIC (pm)OPHTHALMOLOGY CLINIC - OROPHTHALMOLOGY CLINIC -PHCOPHTHALMOLOGY CLINIC -PHC 2OPTHA (PRE OPERATION)OPTHA SPECIALIST CLINIC-2OPTOMETRY  CLINIC 1OPTOMETRY CLINIC  FEMALEOPTOMETRY CLINIC 2OR - 5 -CS ROOMORTHO  CLINIC -2ORTHO (consultant) CLINIC (pm)ORTHO CLINIC 2 PMORTHO EMERGENCY 2ORTHOCLINIC -PHC ORTHOPEDIC CONSULTANT (AM)OSREAPROSSIS 2OSTEOPOROSIS RADIOLOGYOUTPATIENT PHARMACYObstetricsOccupational Therapy (Male)OncologyOphthalmology Clinic (pm)Ophthalmology Pre OperationOpthalmicOpticalOral/Maxillofacial SurgeryOrtho clinic 2  (Pm)OrthopedicOutpatientPATIENT RELATIONSPEDIA SCREENINGPEDIA SCREENING-PHCPEDIA SURGERYPEDIA SURGERY-PHCPEDIATIC CARDIOLOGY CLINICPEDIATIC NEUROLOGY CLINICPEDIATRIC INTENSIVE CARE UNIT -PICUPEDIATRICS  CLINC VCPEDIATRICS ( AIIAT HILAL )PEDIATRICS ( AYMAN )PEDIATRICS ( DALIA )PEDIATRICS CLINIC -1PEDIATRICS CLINIC -2PHARMACY MAIN STOREPHARMACY REFILL (FEMALE)PHARMACY REFILL (MALE)PHYSIOTHERAPY FEMALEPHYSIOTHERAPY FEMALE CLINICPHYSIOTHERAPY HOME HEALTH CAREPHYSIOTHERAPY MALEPHYSIOTHERAPY MALE CLINICPLASTIC SURGERY CLINICPOST BARIATRIC SURGERY CLINICPOST DISCHARGE CLINICPRE OPPREGNANCY CLINCPREMARITAL SCREENING CLINICPRIMARY CLINIC FOR APPPROCEDURE ROOM 1PSORIASISPSYCHIATRIC MEDICAL COMMITTEEPSYCHIATRY CLINICPSYCHIATRY CLINIC VCPSYCHIATRY CLINIC-PHCPSYCHIATRY PEDIATIC CLINICPSYCHOLOGIST CLINIC 1PSYCHOLOGIST CLINIC 2PaediatricsPalliative pain clinic Management Pediatric SurgeryPediatrics Clinic - 4Pediatrics Clinic -3PharmacyPhysiotherapyPlastic SurgeryPre-Employment Check upPre-Marital Check upPre-School Check upPreventive CarePsychiatryPulmonologyRADIOLOGY - DEPARTMENTRADIOLOGY DEPARTMENTRADIOLOGY LIBRARY **RADIOLOGY REGRDURE-FIL CLINIC APPREFIL MOBILEREFILLRL CLINICRENAL CLINICRENAL CLINIC (1)RENAL DIALYSISREPRODUCTIVE CLINICRESUSCITATION ROOMRHEUMATOLOGY - 2RHEUMATOLOGY CLINIC 1RheumatologyRheumatology Clinic 2SCREENING  CLINIC 2SCREENING CLINIC-PHC 1SCREENING PHC CLINICSOCIAL WORKER CLINICSOCIAL WORKER HOME HEALTH CARESPEECH CLINICSPEECH THERAPY (female)SPEECH THERAPY CLINICSPIROMETRY CLINICSpeech Therapy (Male)Speech Therapy / Behavioral and developmental pediatric Steam DeviceSugar Measuring DeviceTEAM HOME HEALTH CARETEST CLINICTHORACIC SURGERYUCCULTRASOUNDULTRASOUND CLINIC 1ULTRASOUND CLINIC 2URGENT CARE CLINIC 1URGENT CARE CLINIC 2UROFLOWMETRY CLINCUROLOGY (PRE OPERATION)UROLOGY CLINIC 1UROLOGY CLINIC 2UROLOGY CLINIC 3UROLOGY CLINIC VCUROLOGY CLINIC-PHCUROLOGY CLINIC-PHC (Mawed)UROLOGY CLINIC-PHC2UROLOGY ORUrologyVACCINATION COVID-19VASCULAR SURGERY CLINICVascular SurgeryWARD - C2WARD -C1WARD A1WARD B1WARD B2WARD D2WARD- A2WEAPON VALIDATION CLINICWOUND CAREYOUSEF TEST CLINICchochlear implantdentla implant dermatology consultantimplantinpatient-testob gyn clinicoccupational therapy (female)ophthalmology or ophthalmology phc 3 ophthalmology phc 4 ophthalmology phc 5ophthalmology specialist clinic 1 optometry clinic 3 optometry clinic 4optometry phc pediatric occupational therapypost op surgery clinicpppproom - 1room - 3room - 4room 5room- 2testtesttest-hussam2test-hussam_edittest1test11test2test20test3test30test4test5test6yFilterDoctorFilter by DoctorPatient TypeAllInsuranceCashAllBill TypeAllNo servicesBilledPartially BilledRefundedNot BilledAllPayer... jnhjghnb SAAUDI(The Mediterranean &amp; Gulf Cooperative Insurance &amp; Reinsurance Company (MedGulf???????????Accumed Comany123132020-NACIG - TCSACIG- MEDNETAdnicAICI captialAJHAHAL ETIHADAl Sagr Cooperative  Insurance CompanyALBAHAALFA131ALJazira TakafulALJUMAIH COallamAllianz Saudi Fransi Insurance CompanyAlrajhi Takaful for Cooperative InsuranceAMANA INSURANCEARABIA InsuranceARABIAN SHEILDArabian Shield cooperative Insurance CompanyARAMCOARAMCO ACTIVEARAMCO OTHERAXA Cooperative Insurance CompanybandrbupaBupaBUPA Arabia for Cooperative InsuranceBURUJCORP-CompanycxzcvDamanDate SeptEnvironmentETIHADfgfdgfvdgcfhgnvbGENERAL 2021GENERAL-2020-JgggGLOBEMEDGLOBEMED SAUDI ( GMS )GLOBEMED SAUDI ( GMS )GM-AMINAHGOSIGULF GENERAL - MEDNETGULF GENERAL - TCSGulf general Insurance CompanyGulf unionGulf Union Cooperative Insurance CompanytesthghgfdfdHKK Coinsurance company nameinsuranceTestIUYJUIJHAHJPJubil InsKHAMISKSAKSAKSA001KSA01KSAAMalath Cooperative Insurance &amp; Reinsurance CompanymaxmazMEDNETMNAMEMOHMOUNIRMS-NIZIHAmyNextcareOmanregrgergergrrrRTRSAGR - MEDNETSALAMA INSURANCEsaudiSaudi Arabian cooperative Insurance Company (Saico)Saudi Enaya Cooperative InsuranceSaudi United  Cooperative Insurance  (WALA'A)saudi1sdfsSelf Pay - CashsolidaritysosoSPSRSYTawuniya cooperative  Insurance CompanyTCStesttest2020testAL RAJHItestAL SAGR - NEXTCAREtestMalathtestMalath CooperativetestMedGulftestRAJHIAAtestSAICOtestSAUDI ENAYAtestSGH STAFF - TAWUNIYAtestTAWUNIYAtestTawuniya cooperative Insurance CompanytestWALAAtestWALAA - NEXTCAREThe Mediterranean and Gulf Cooperative Insurance and Reinsurance Company (MEDIVISA/MEDGULF)ticnToday-27-07TOKIO MARINETOTAL CARE TOTAL CARE SAUDI (TCS)TRADE UNIONUAEUCAUNSPECIFIEDyamamahyt...ClaimLineCreated ByLast Update ByDetailsew yr JJH8/*9APM-OP-000304102/11/202202/11/202202/11/202202/11/202289740.325/8184876479BLOOD BANKDr. ABDULAZIZ ALDAWSARIInsuranceBilled101|Tawuniya cooperative  Insurance Company1003373root/2022-11-01 23:31:16.247root/2022-11-01 23:31:16.247ui-button




Claim Audit#Login UserAudit DateClaim IDAction TypeAction IdentifierUpdated FieldsHIS Msg IdHIS Msg ActionHIS Msg Type
                1
            root01\11\22 23:31:161003373ADD CLAIMVISIT NO= &quot;APM-OP-0003041&quot;
                2
            root02\11\22 00:14:461003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot;
                3
            root02\11\22 00:17:311003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot; PAYER_ID=&quot;101&quot; CONTRACT_PACKAGE_NAME=&quot;&quot; MEMBER_ID=&quot;2.025&quot; PATIENT_INSURANCE_ID=&quot;54935&quot;
                4
            root02\11\22 00:17:311003373UPDATE ENCOUNTERVISIT NO= &quot;APM-OP-0003041&quot;
                5
            root02\11\22 00:24:531003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot; MEMBER_ID=&quot;789.20&quot; PATIENT_INSURANCE_ID=&quot;54937&quot;
                6
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;900280200&quot;
                7
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;1002034&quot;
                8
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;920580100&quot;
                9
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;907640000&quot;
                10
            root02\11\22 00:36:321003373UPDATE ACTIVITYACTIVITY CODE= &quot;920580100&quot; NET_AMOUNT=&quot;528.77&quot; PATIENT_SHARE=&quot;58.75&quot; GROSS_AMOUNT=&quot;587.52&quot; DISCOUNT_AMOUNT=&quot;146.88&quot; DEDUCTIBLE_AMOUNT=&quot;0.00&quot; CO_PAYMENT_AMOUNT=&quot;58.75&quot;FP123NE</value>
      <webElementGuid>c3c58783-e692-49db-afc5-ae2ee0ec7758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt190&quot;)/div[@class=&quot;ui-layout-unit-content ui-widget-content&quot;]</value>
      <webElementGuid>ba967eb3-2eb1-4bb7-9f71-2d23db14c42d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt190']/div</value>
      <webElementGuid>d5ec8256-59cf-42c8-bbc6-a163b88ae6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGOUT'])[1]/following::div[2]</value>
      <webElementGuid>21b2e156-acc1-47a0-bc32-c97308796964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Info'])[1]/following::div[2]</value>
      <webElementGuid>60176338-a59d-4e66-ac95-0e7e5bb47077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>f990767e-a091-4258-8c6a-ccf0ff06d48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;


HomePatient Journey ManagementData Entryfocus = function() {PrimeFaces.ab({s:&quot;mainForm:j_idt192&quot;,f:&quot;mainForm&quot;,u:&quot;mainForm:facilityLicense&quot;,onco:function(xhr,status,args){checkChangeLicense();;},pa:arguments[0]});};$(function() {focus();});



$(function(){PrimeFaces.cw(&quot;Poll&quot;,&quot;checkModifiedChangedPoll&quot;,{id:&quot;phWLForm:checkModifiedChangedPoll&quot;,frequency:30000,autoStart:true,fn:function(){PrimeFaces.ab({s:&quot;phWLForm:checkModifiedChangedPoll&quot;,f:&quot;phWLForm&quot;,g:false});}});});onload = function() {PrimeFaces.ab({s:&quot;phWLForm:j_idt193&quot;,f:&quot;phWLForm&quot;,pa:arguments[0]});};$(function() {onload();});


Create New Visit Ammar

Search
Rerouted from Coding stage.








                                    Create New VisitExportui-button
                                    
                                    

                                       FP1NE Rows Per Page20304050607080
                                PatientFilter by PatientMRNFilter by MRNVisit NoFilter by Visit NoAdmission DateAdmission Date 
                                      
                                    Discharge DateDischarge Date 
                                      
                                    National IDFilter by National IDPhoneDepartment(DIABETES VIRTUAL INSULIN PUMP ) CLINIC--666??????? ??????? ???????????????? ????????A1C  PROJECT CLINICACCIDENT &amp; EMERGENCYADENO-TONSILLECTOMYADULT DIETITAN CLNIC MALEADULT INSULIN PUMP CLINICANESTHESIA CLINICANTI SMOKING CLINICAUDIOLOGY AND BALANCE CLINICAllergy/ImunologyyuyyyAnesthesia Clinic (AM)Anesthesia Clinic (PM)Artificial LimbsBABY COT WARD-BCBARIATRIC SURGERY CLINICBLOOD BANKBOARDING FAST TRACKBOARDING FEMALE MEDICALBOARDING MALE MEDICALBOARDING PEDIATRICBOARDING RESUS ROOMBOARDING TRAUMABUSINESS CENTERBusiness Trip Check upCARDIOLOGIST - CONSULTANTCARDIOLOGY CLINICCARDIOLOGY CLINIC - 2 AMCARDIOLOGY ECHOCARDIOGRAHPYCARDIOLOGY SCREENING CLINICCHILDHOOD DEVELOPMENTAL AND BEHAVIORAL DISORDERSCHILDHOOD DEVELOPMENTAL AND BEHAVIORAL DISORDERS 2CLINIC GALLSTONESCONSULTING PHARMACYCardiologyCardiology Clinic - 2 PMCardiothoracic SurgeryDANTAL-GPC CLINIC-5DAY SURGERY UNIT D1 DSUDCC PHARMACYDCC PHARMACY (1)DELIVERY ROOMDELIVERY ROOM-1DELIVERY ROOM-2DELIVERY ROOM-3DELIVERY ROOM-4DELIVERY ROOM-5DELIVERY ROOM-6DELIVERY ROOM-7DELIVERY ROOM-8DELIVERY ROOM-9DENTAL  CLINIC 9DENTAL CLINIC -PHC 1DENTAL CLINIC -PHC 2DENTAL CLINIC -PHC 2 (1)DENTAL CLINIC 1DENTAL CLINIC 10DENTAL CLINIC 11DENTAL CLINIC 2DENTAL CLINIC 3DENTAL CLINIC 4DENTAL CLINIC 5DENTAL CLINIC 6DENTAL CLINIC 7DENTAL CLINIC 8DENTAL CLINIC PHC 5DENTAL CLINIC PHC 6DENTAL HYGINE -12DERMA CLINIC VCDERMA FINGERPRINTDERMA(NAEL HATATAH) CLINICDERMATOLOGY (  LASER )DERMATOLOGY (DR.ALI) CLINICDERMATOLOGY (FEMALE RESIDENT)CLINICDERMATOLOGY 1DERMATOLOGY 2DERMATOLOGY CLINIC 3DERMATOLOGY PHC (PM)DERMATOLOGY PHC CLINICDERMATOLOGY PHC CLINIC - 2DERMATOLOGY VIRTUAL CLINIC-PMDEVELOPMENTAL AND BEHAVIORAL DISORDER CLINIC 2 DEVELOPMENTAL AND BEHAVIORAL DISORDERS ( screening)  PHC 2DEVELOPMENTAL PEDIATRIC VCDEXA SCANDIABATIC PITUTARY GLAND CLINICDIABETES  ENDOCRINE PEDIA &amp; ADOLESCNCE 2DIABETES  ENDOCRINE PEDIA-5DIABETES  FOLLOWUP CLINICDIABETES  FOLLOWUP CLINIC 1DIABETES  FOLLOWUP CLINIC 2DIABETES ANDROLOGY CLINICDIABETES BLOOD EXRTACTION (FEMALE)DIABETES BLOOD EXRTACTION (MALE)DIABETES CARDIOLOGY CLINIC-1DIABETES CARDIOLOGY CLINIC-2DIABETES CLINIC - 1DIABETES CLINIC - 10DIABETES CLINIC - 2DIABETES CLINIC - 6DIABETES CLINIC - 7DIABETES CLINIC - 8 (DR SALEH)DIABETES CLINIC - 9DIABETES CLINIC 4DIABETES CLINIC 5 (DR.SAEED)DIABETES CLINIC-3DIABETES COMPANY CLINICDIABETES DIETITIAN CLINICDIABETES EDUCATION CLINICDIABETES ENDOCARIONOLOGY PEDIA &amp; ADOLESCENEDIABETES ENDOCRINE PEDIA-3DIABETES ENDOCRINE SURGERYDIABETES ENDOCRINOLOGY - 6DIABETES ENDOCRINOLOGY -1DIABETES ENDOCRINOLOGY -3DIABETES ENDOCRINOLOGY 5DIABETES ENDOCRINOLOGY 5 (1)DIABETES ENDOCRINOLOGY 7DIABETES ENDOCRINOLOGY SCREENINGDIABETES ENDOCRINOLOGY-2DIABETES ENDOCRINOLOGY-4DIABETES FEMALE SCREENING CLINICDIABETES GESTATIONAL CLINICDIABETES INSULIN PUMP PEDIA &amp; ADOLESCENDIABETES INTENSIVE INSULIN THERAPY CLINICDIABETES MALE SCREENING CLINICDIABETES MULTI DISCIPLINARY CLINICDIABETES NEPHROLOGY CLINICDIABETES NEUROLOGY CLINICDIABETES NEUROLOGY CLINIC-2DIABETES OBESITY CLINICDIABETES OBESTARIC CLINICDIABETES OPTHALMOLOGY CLINICDIABETES OPTOMETRIC CLINICDIABETES ORAL HYGIENE CLINICDIABETES OSTEOPOROSIS CLINICDIABETES OSTEOPOROSIS CLINIC 2DIABETES PEDIA  &amp; ADOLESCENCE CLINIC 1DIABETES PEDIA &amp; ADOLESCENCE /SCREEINGDIABETES PEDIA CLINIC - 4DIABETES PEDIA DIETITIAN CLINICDIABETES PEDIA EDUCATOR CLINICDIABETES PEDIA SCREENINGDIABETES PHYSICAL EXERCISE CLINICDIABETES PRECONCEPTION COUNSELLINGDIABETES PRIMARY HEALTH CARE CLINICDIABETES PSYCHIATRY CLINICDIABETES PSYCHOLOGIST (2)DIABETES PSYCHOLOGIST(1)DIABETES REAFL RX (FEMALE)DIABETES SCREENING GASTATIONALDIABETES TRANSITIONAL CLINICDIABETES TYPES 1 CLINICDIABETES VIRTUAL  CLINICDIABETIC OBESITY CLINIC 2DIABETIC OSTEOPOROSIS FRACTURES CLINICDIABETIC PODIATRIC CLINIC -1 DIABETIC PODIATRIC CLINIC -2DIABETIC PODIATRIC CLINIC -3DIABETIC PODIATRIC CLINIC -4DIABETIC REFILLRL CLINICDIABETIES CLINIC 8DIALYSISDR FAISAL ALAQILI CHEST CLINICDYSLIPEDEMIA CLINICDentalDermaVenDevelopment and Behavior disorders ( screening) PHC Development and Behavior disorders ( screening) PHC 3Diabetic Dental Clinic -1Diabetic Dental Clinic -2DialysisECHO UNIT EMERGENCYEMPLOYEES CLINICENDOSCOPYENDOSCOPY (ENDO)ENDOSCOPY CLINICENDOSCOPY UNITENTENT (PRE OPERATION)ENT CLINIC - PHCENT CLINIC -1ENT CLINIC -2ENT CLINIC -3 ENT CLINIC VCER PHARMACYESWL CLINCEVALUATION HOME HEALTH CAREEmergencyEndocrinologyEndoscopy (END2)Endoscopy clinic-ERFIRST VISIT-PHCFOLLOWUP DEPARTMENTFURNITURE MAIN STOREFamily PracticeFive days programGALLSTONES CLINICGASTRO - 2GASTRO - CONSULTANTGASTRO - SPECIALISTGASTROENTEROLOGY CLINICGASTROENTROLOGY CLINIC (AM)GB STONES CLINIC PHC ONLYGENERAL SUREGERY CLINIC - 3GENERAL SUREGERY CLINIC -1GENERAL SUREGERY CLINIC -2GENERAL SUREGERY SPECIALISTGENERAL SUREGERY-PHCGENERAL SUREGERY-PHC 2GENERAL SUREGEY CLINC VCGENERAL SURGERY - 4GastroenterologyGastroentrology Clinic (pm)General Medical Check upGeneral PracticesGeneral SurgeryGeneral SurgeryGerontologyGynecologyHEMATOLOGY (GHUZAYEL)HEMATOLOGY ONCOLOGY CLINICHEMATOLOGY ONCOLOGY CLINIC 2 HEPATOBILIARYHEPATOLOGY CLINICHIGH RISK DIABETES CLINICHOSAM CLINICHOSPITAL DIRECTORHearing AidsHematologyHematology Oncology Clinic 3Hematology clinic 5HepatologyHome Health CareINFECTION CONTROLINFECTIOUS DISEASES CLINCINPATIENT PHARMACYINT MED SCREENING CLINIC-PHC 2INT MEDICIN ( DR JIHAN MAHMOUD ) CHEST CLINICINT MEDICIN ( RASHA )CLINICINT MEDICIN (DR ABDUL BASSET)CLINICINT MEDICIN (DR ADAWEYAH)CLINICINT MEDICIN (DR MOHAMAD RAMADAN)INT MEDICIN (DR MOHAMAD RAMADAN) CHEST CLINICINT MEDICIN (DR MOHAMAD SAFI)CLINICINT MEDICIN (KAMAL)CLINICINT MEDICIN CLINIC ( ALI ALQAHTANI )INT MEDICIN CLINIC ( WEAAM AHMED )INT MEDICIN VCINTENSIVE CARE UNIT -ICUINTERNAL  MEDICIN CLINIC (MESHAL ALENEZI )INTERNAL MEDICINEINTERNAL MEDICINE - CONSULTANTIndustrial Check upInfectious Disease CLINICInfectious DiseasesInpatientInternal MedicineIqama Issuance and  Renewal Check upKING SALMAN HOSPITALLABORATORY - DEPARTMENTLABORATORY MAIN STORELAUNDEYLEGAL AFFAIRSLIVE QUALITY MAIN STORE W HOUSEMAXILLOFACIAL SURGERYMEDICAL DIRECTORMEDICAL RECORDS DEPARTMENTSMEDICAL REPORTSMOH DIABATIC  CLINICMOH HOSPITAL - DBAMORTUARYMaternityMedical report clinicNEONATAL INTENSIVE CARE UNIT (NICU)NEPHROLOGY CLINICNEURO MEDICALNEURO SURGERY VCNEUROLOGY CLINICNEUROLOGY CLINIC VCNEUROSURGERY CLINIC (am)NURSING HOME HEALTH CARENUTRITION CLINICNeonatal-Perinatal MedicineNephrologyNeuro-SurgeryNeurologyNeurosurgery Clinic (pm)Non electronic wheel chairNuclear MedicineOB / GYNE CLINIC - 3OB GYNE CLINICOCCUPATIONAL THERAPYOPD BLOOD EXTRACTION-FEMALEOPD BLOOD EXTRACTION-MALEOPHTHALMOLOGY CLINIC (pm)OPHTHALMOLOGY CLINIC - OROPHTHALMOLOGY CLINIC -PHCOPHTHALMOLOGY CLINIC -PHC 2OPTHA (PRE OPERATION)OPTHA SPECIALIST CLINIC-2OPTOMETRY  CLINIC 1OPTOMETRY CLINIC  FEMALEOPTOMETRY CLINIC 2OR - 5 -CS ROOMORTHO  CLINIC -2ORTHO (consultant) CLINIC (pm)ORTHO CLINIC 2 PMORTHO EMERGENCY 2ORTHOCLINIC -PHC ORTHOPEDIC CONSULTANT (AM)OSREAPROSSIS 2OSTEOPOROSIS RADIOLOGYOUTPATIENT PHARMACYObstetricsOccupational Therapy (Male)OncologyOphthalmology Clinic (pm)Ophthalmology Pre OperationOpthalmicOpticalOral/Maxillofacial SurgeryOrtho clinic 2  (Pm)OrthopedicOutpatientPATIENT RELATIONSPEDIA SCREENINGPEDIA SCREENING-PHCPEDIA SURGERYPEDIA SURGERY-PHCPEDIATIC CARDIOLOGY CLINICPEDIATIC NEUROLOGY CLINICPEDIATRIC INTENSIVE CARE UNIT -PICUPEDIATRICS  CLINC VCPEDIATRICS ( AIIAT HILAL )PEDIATRICS ( AYMAN )PEDIATRICS ( DALIA )PEDIATRICS CLINIC -1PEDIATRICS CLINIC -2PHARMACY MAIN STOREPHARMACY REFILL (FEMALE)PHARMACY REFILL (MALE)PHYSIOTHERAPY FEMALEPHYSIOTHERAPY FEMALE CLINICPHYSIOTHERAPY HOME HEALTH CAREPHYSIOTHERAPY MALEPHYSIOTHERAPY MALE CLINICPLASTIC SURGERY CLINICPOST BARIATRIC SURGERY CLINICPOST DISCHARGE CLINICPRE OPPREGNANCY CLINCPREMARITAL SCREENING CLINICPRIMARY CLINIC FOR APPPROCEDURE ROOM 1PSORIASISPSYCHIATRIC MEDICAL COMMITTEEPSYCHIATRY CLINICPSYCHIATRY CLINIC VCPSYCHIATRY CLINIC-PHCPSYCHIATRY PEDIATIC CLINICPSYCHOLOGIST CLINIC 1PSYCHOLOGIST CLINIC 2PaediatricsPalliative pain clinic Management Pediatric SurgeryPediatrics Clinic - 4Pediatrics Clinic -3PharmacyPhysiotherapyPlastic SurgeryPre-Employment Check upPre-Marital Check upPre-School Check upPreventive CarePsychiatryPulmonologyRADIOLOGY - DEPARTMENTRADIOLOGY DEPARTMENTRADIOLOGY LIBRARY **RADIOLOGY REGRDURE-FIL CLINIC APPREFIL MOBILEREFILLRL CLINICRENAL CLINICRENAL CLINIC (1)RENAL DIALYSISREPRODUCTIVE CLINICRESUSCITATION ROOMRHEUMATOLOGY - 2RHEUMATOLOGY CLINIC 1RheumatologyRheumatology Clinic 2SCREENING  CLINIC 2SCREENING CLINIC-PHC 1SCREENING PHC CLINICSOCIAL WORKER CLINICSOCIAL WORKER HOME HEALTH CARESPEECH CLINICSPEECH THERAPY (female)SPEECH THERAPY CLINICSPIROMETRY CLINICSpeech Therapy (Male)Speech Therapy / Behavioral and developmental pediatric Steam DeviceSugar Measuring DeviceTEAM HOME HEALTH CARETEST CLINICTHORACIC SURGERYUCCULTRASOUNDULTRASOUND CLINIC 1ULTRASOUND CLINIC 2URGENT CARE CLINIC 1URGENT CARE CLINIC 2UROFLOWMETRY CLINCUROLOGY (PRE OPERATION)UROLOGY CLINIC 1UROLOGY CLINIC 2UROLOGY CLINIC 3UROLOGY CLINIC VCUROLOGY CLINIC-PHCUROLOGY CLINIC-PHC (Mawed)UROLOGY CLINIC-PHC2UROLOGY ORUrologyVACCINATION COVID-19VASCULAR SURGERY CLINICVascular SurgeryWARD - C2WARD -C1WARD A1WARD B1WARD B2WARD D2WARD- A2WEAPON VALIDATION CLINICWOUND CAREYOUSEF TEST CLINICchochlear implantdentla implant dermatology consultantimplantinpatient-testob gyn clinicoccupational therapy (female)ophthalmology or ophthalmology phc 3 ophthalmology phc 4 ophthalmology phc 5ophthalmology specialist clinic 1 optometry clinic 3 optometry clinic 4optometry phc pediatric occupational therapypost op surgery clinicpppproom - 1room - 3room - 4room 5room- 2testtesttest-hussam2test-hussam_edittest1test11test2test20test3test30test4test5test6yFilterDoctorFilter by DoctorPatient TypeAllInsuranceCashAllBill TypeAllNo servicesBilledPartially BilledRefundedNot BilledAllPayer... jnhjghnb SAAUDI(The Mediterranean &amp; Gulf Cooperative Insurance &amp; Reinsurance Company (MedGulf???????????Accumed Comany123132020-NACIG - TCSACIG- MEDNETAdnicAICI captialAJHAHAL ETIHADAl Sagr Cooperative  Insurance CompanyALBAHAALFA131ALJazira TakafulALJUMAIH COallamAllianz Saudi Fransi Insurance CompanyAlrajhi Takaful for Cooperative InsuranceAMANA INSURANCEARABIA InsuranceARABIAN SHEILDArabian Shield cooperative Insurance CompanyARAMCOARAMCO ACTIVEARAMCO OTHERAXA Cooperative Insurance CompanybandrbupaBupaBUPA Arabia for Cooperative InsuranceBURUJCORP-CompanycxzcvDamanDate SeptEnvironmentETIHADfgfdgfvdgcfhgnvbGENERAL 2021GENERAL-2020-JgggGLOBEMEDGLOBEMED SAUDI ( GMS )GLOBEMED SAUDI ( GMS )GM-AMINAHGOSIGULF GENERAL - MEDNETGULF GENERAL - TCSGulf general Insurance CompanyGulf unionGulf Union Cooperative Insurance CompanytesthghgfdfdHKK Coinsurance company nameinsuranceTestIUYJUIJHAHJPJubil InsKHAMISKSAKSAKSA001KSA01KSAAMalath Cooperative Insurance &amp; Reinsurance CompanymaxmazMEDNETMNAMEMOHMOUNIRMS-NIZIHAmyNextcareOmanregrgergergrrrRTRSAGR - MEDNETSALAMA INSURANCEsaudiSaudi Arabian cooperative Insurance Company (Saico)Saudi Enaya Cooperative InsuranceSaudi United  Cooperative Insurance  (WALA&quot; , &quot;'&quot; , &quot;A)saudi1sdfsSelf Pay - CashsolidaritysosoSPSRSYTawuniya cooperative  Insurance CompanyTCStesttest2020testAL RAJHItestAL SAGR - NEXTCAREtestMalathtestMalath CooperativetestMedGulftestRAJHIAAtestSAICOtestSAUDI ENAYAtestSGH STAFF - TAWUNIYAtestTAWUNIYAtestTawuniya cooperative Insurance CompanytestWALAAtestWALAA - NEXTCAREThe Mediterranean and Gulf Cooperative Insurance and Reinsurance Company (MEDIVISA/MEDGULF)ticnToday-27-07TOKIO MARINETOTAL CARE TOTAL CARE SAUDI (TCS)TRADE UNIONUAEUCAUNSPECIFIEDyamamahyt...ClaimLineCreated ByLast Update ByDetailsew yr JJH8/*9APM-OP-000304102/11/202202/11/202202/11/202202/11/202289740.325/8184876479BLOOD BANKDr. ABDULAZIZ ALDAWSARIInsuranceBilled101|Tawuniya cooperative  Insurance Company1003373root/2022-11-01 23:31:16.247root/2022-11-01 23:31:16.247ui-button




Claim Audit#Login UserAudit DateClaim IDAction TypeAction IdentifierUpdated FieldsHIS Msg IdHIS Msg ActionHIS Msg Type
                1
            root01\11\22 23:31:161003373ADD CLAIMVISIT NO= &quot;APM-OP-0003041&quot;
                2
            root02\11\22 00:14:461003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot;
                3
            root02\11\22 00:17:311003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot; PAYER_ID=&quot;101&quot; CONTRACT_PACKAGE_NAME=&quot;&quot; MEMBER_ID=&quot;2.025&quot; PATIENT_INSURANCE_ID=&quot;54935&quot;
                4
            root02\11\22 00:17:311003373UPDATE ENCOUNTERVISIT NO= &quot;APM-OP-0003041&quot;
                5
            root02\11\22 00:24:531003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot; MEMBER_ID=&quot;789.20&quot; PATIENT_INSURANCE_ID=&quot;54937&quot;
                6
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;900280200&quot;
                7
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;1002034&quot;
                8
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;920580100&quot;
                9
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;907640000&quot;
                10
            root02\11\22 00:36:321003373UPDATE ACTIVITYACTIVITY CODE= &quot;920580100&quot; NET_AMOUNT=&quot;528.77&quot; PATIENT_SHARE=&quot;58.75&quot; GROSS_AMOUNT=&quot;587.52&quot; DISCOUNT_AMOUNT=&quot;146.88&quot; DEDUCTIBLE_AMOUNT=&quot;0.00&quot; CO_PAYMENT_AMOUNT=&quot;58.75&quot;FP123NE&quot;) or . = concat(&quot;


HomePatient Journey ManagementData Entryfocus = function() {PrimeFaces.ab({s:&quot;mainForm:j_idt192&quot;,f:&quot;mainForm&quot;,u:&quot;mainForm:facilityLicense&quot;,onco:function(xhr,status,args){checkChangeLicense();;},pa:arguments[0]});};$(function() {focus();});



$(function(){PrimeFaces.cw(&quot;Poll&quot;,&quot;checkModifiedChangedPoll&quot;,{id:&quot;phWLForm:checkModifiedChangedPoll&quot;,frequency:30000,autoStart:true,fn:function(){PrimeFaces.ab({s:&quot;phWLForm:checkModifiedChangedPoll&quot;,f:&quot;phWLForm&quot;,g:false});}});});onload = function() {PrimeFaces.ab({s:&quot;phWLForm:j_idt193&quot;,f:&quot;phWLForm&quot;,pa:arguments[0]});};$(function() {onload();});


Create New Visit Ammar

Search
Rerouted from Coding stage.








                                    Create New VisitExportui-button
                                    
                                    

                                       FP1NE Rows Per Page20304050607080
                                PatientFilter by PatientMRNFilter by MRNVisit NoFilter by Visit NoAdmission DateAdmission Date 
                                      
                                    Discharge DateDischarge Date 
                                      
                                    National IDFilter by National IDPhoneDepartment(DIABETES VIRTUAL INSULIN PUMP ) CLINIC--666??????? ??????? ???????????????? ????????A1C  PROJECT CLINICACCIDENT &amp; EMERGENCYADENO-TONSILLECTOMYADULT DIETITAN CLNIC MALEADULT INSULIN PUMP CLINICANESTHESIA CLINICANTI SMOKING CLINICAUDIOLOGY AND BALANCE CLINICAllergy/ImunologyyuyyyAnesthesia Clinic (AM)Anesthesia Clinic (PM)Artificial LimbsBABY COT WARD-BCBARIATRIC SURGERY CLINICBLOOD BANKBOARDING FAST TRACKBOARDING FEMALE MEDICALBOARDING MALE MEDICALBOARDING PEDIATRICBOARDING RESUS ROOMBOARDING TRAUMABUSINESS CENTERBusiness Trip Check upCARDIOLOGIST - CONSULTANTCARDIOLOGY CLINICCARDIOLOGY CLINIC - 2 AMCARDIOLOGY ECHOCARDIOGRAHPYCARDIOLOGY SCREENING CLINICCHILDHOOD DEVELOPMENTAL AND BEHAVIORAL DISORDERSCHILDHOOD DEVELOPMENTAL AND BEHAVIORAL DISORDERS 2CLINIC GALLSTONESCONSULTING PHARMACYCardiologyCardiology Clinic - 2 PMCardiothoracic SurgeryDANTAL-GPC CLINIC-5DAY SURGERY UNIT D1 DSUDCC PHARMACYDCC PHARMACY (1)DELIVERY ROOMDELIVERY ROOM-1DELIVERY ROOM-2DELIVERY ROOM-3DELIVERY ROOM-4DELIVERY ROOM-5DELIVERY ROOM-6DELIVERY ROOM-7DELIVERY ROOM-8DELIVERY ROOM-9DENTAL  CLINIC 9DENTAL CLINIC -PHC 1DENTAL CLINIC -PHC 2DENTAL CLINIC -PHC 2 (1)DENTAL CLINIC 1DENTAL CLINIC 10DENTAL CLINIC 11DENTAL CLINIC 2DENTAL CLINIC 3DENTAL CLINIC 4DENTAL CLINIC 5DENTAL CLINIC 6DENTAL CLINIC 7DENTAL CLINIC 8DENTAL CLINIC PHC 5DENTAL CLINIC PHC 6DENTAL HYGINE -12DERMA CLINIC VCDERMA FINGERPRINTDERMA(NAEL HATATAH) CLINICDERMATOLOGY (  LASER )DERMATOLOGY (DR.ALI) CLINICDERMATOLOGY (FEMALE RESIDENT)CLINICDERMATOLOGY 1DERMATOLOGY 2DERMATOLOGY CLINIC 3DERMATOLOGY PHC (PM)DERMATOLOGY PHC CLINICDERMATOLOGY PHC CLINIC - 2DERMATOLOGY VIRTUAL CLINIC-PMDEVELOPMENTAL AND BEHAVIORAL DISORDER CLINIC 2 DEVELOPMENTAL AND BEHAVIORAL DISORDERS ( screening)  PHC 2DEVELOPMENTAL PEDIATRIC VCDEXA SCANDIABATIC PITUTARY GLAND CLINICDIABETES  ENDOCRINE PEDIA &amp; ADOLESCNCE 2DIABETES  ENDOCRINE PEDIA-5DIABETES  FOLLOWUP CLINICDIABETES  FOLLOWUP CLINIC 1DIABETES  FOLLOWUP CLINIC 2DIABETES ANDROLOGY CLINICDIABETES BLOOD EXRTACTION (FEMALE)DIABETES BLOOD EXRTACTION (MALE)DIABETES CARDIOLOGY CLINIC-1DIABETES CARDIOLOGY CLINIC-2DIABETES CLINIC - 1DIABETES CLINIC - 10DIABETES CLINIC - 2DIABETES CLINIC - 6DIABETES CLINIC - 7DIABETES CLINIC - 8 (DR SALEH)DIABETES CLINIC - 9DIABETES CLINIC 4DIABETES CLINIC 5 (DR.SAEED)DIABETES CLINIC-3DIABETES COMPANY CLINICDIABETES DIETITIAN CLINICDIABETES EDUCATION CLINICDIABETES ENDOCARIONOLOGY PEDIA &amp; ADOLESCENEDIABETES ENDOCRINE PEDIA-3DIABETES ENDOCRINE SURGERYDIABETES ENDOCRINOLOGY - 6DIABETES ENDOCRINOLOGY -1DIABETES ENDOCRINOLOGY -3DIABETES ENDOCRINOLOGY 5DIABETES ENDOCRINOLOGY 5 (1)DIABETES ENDOCRINOLOGY 7DIABETES ENDOCRINOLOGY SCREENINGDIABETES ENDOCRINOLOGY-2DIABETES ENDOCRINOLOGY-4DIABETES FEMALE SCREENING CLINICDIABETES GESTATIONAL CLINICDIABETES INSULIN PUMP PEDIA &amp; ADOLESCENDIABETES INTENSIVE INSULIN THERAPY CLINICDIABETES MALE SCREENING CLINICDIABETES MULTI DISCIPLINARY CLINICDIABETES NEPHROLOGY CLINICDIABETES NEUROLOGY CLINICDIABETES NEUROLOGY CLINIC-2DIABETES OBESITY CLINICDIABETES OBESTARIC CLINICDIABETES OPTHALMOLOGY CLINICDIABETES OPTOMETRIC CLINICDIABETES ORAL HYGIENE CLINICDIABETES OSTEOPOROSIS CLINICDIABETES OSTEOPOROSIS CLINIC 2DIABETES PEDIA  &amp; ADOLESCENCE CLINIC 1DIABETES PEDIA &amp; ADOLESCENCE /SCREEINGDIABETES PEDIA CLINIC - 4DIABETES PEDIA DIETITIAN CLINICDIABETES PEDIA EDUCATOR CLINICDIABETES PEDIA SCREENINGDIABETES PHYSICAL EXERCISE CLINICDIABETES PRECONCEPTION COUNSELLINGDIABETES PRIMARY HEALTH CARE CLINICDIABETES PSYCHIATRY CLINICDIABETES PSYCHOLOGIST (2)DIABETES PSYCHOLOGIST(1)DIABETES REAFL RX (FEMALE)DIABETES SCREENING GASTATIONALDIABETES TRANSITIONAL CLINICDIABETES TYPES 1 CLINICDIABETES VIRTUAL  CLINICDIABETIC OBESITY CLINIC 2DIABETIC OSTEOPOROSIS FRACTURES CLINICDIABETIC PODIATRIC CLINIC -1 DIABETIC PODIATRIC CLINIC -2DIABETIC PODIATRIC CLINIC -3DIABETIC PODIATRIC CLINIC -4DIABETIC REFILLRL CLINICDIABETIES CLINIC 8DIALYSISDR FAISAL ALAQILI CHEST CLINICDYSLIPEDEMIA CLINICDentalDermaVenDevelopment and Behavior disorders ( screening) PHC Development and Behavior disorders ( screening) PHC 3Diabetic Dental Clinic -1Diabetic Dental Clinic -2DialysisECHO UNIT EMERGENCYEMPLOYEES CLINICENDOSCOPYENDOSCOPY (ENDO)ENDOSCOPY CLINICENDOSCOPY UNITENTENT (PRE OPERATION)ENT CLINIC - PHCENT CLINIC -1ENT CLINIC -2ENT CLINIC -3 ENT CLINIC VCER PHARMACYESWL CLINCEVALUATION HOME HEALTH CAREEmergencyEndocrinologyEndoscopy (END2)Endoscopy clinic-ERFIRST VISIT-PHCFOLLOWUP DEPARTMENTFURNITURE MAIN STOREFamily PracticeFive days programGALLSTONES CLINICGASTRO - 2GASTRO - CONSULTANTGASTRO - SPECIALISTGASTROENTEROLOGY CLINICGASTROENTROLOGY CLINIC (AM)GB STONES CLINIC PHC ONLYGENERAL SUREGERY CLINIC - 3GENERAL SUREGERY CLINIC -1GENERAL SUREGERY CLINIC -2GENERAL SUREGERY SPECIALISTGENERAL SUREGERY-PHCGENERAL SUREGERY-PHC 2GENERAL SUREGEY CLINC VCGENERAL SURGERY - 4GastroenterologyGastroentrology Clinic (pm)General Medical Check upGeneral PracticesGeneral SurgeryGeneral SurgeryGerontologyGynecologyHEMATOLOGY (GHUZAYEL)HEMATOLOGY ONCOLOGY CLINICHEMATOLOGY ONCOLOGY CLINIC 2 HEPATOBILIARYHEPATOLOGY CLINICHIGH RISK DIABETES CLINICHOSAM CLINICHOSPITAL DIRECTORHearing AidsHematologyHematology Oncology Clinic 3Hematology clinic 5HepatologyHome Health CareINFECTION CONTROLINFECTIOUS DISEASES CLINCINPATIENT PHARMACYINT MED SCREENING CLINIC-PHC 2INT MEDICIN ( DR JIHAN MAHMOUD ) CHEST CLINICINT MEDICIN ( RASHA )CLINICINT MEDICIN (DR ABDUL BASSET)CLINICINT MEDICIN (DR ADAWEYAH)CLINICINT MEDICIN (DR MOHAMAD RAMADAN)INT MEDICIN (DR MOHAMAD RAMADAN) CHEST CLINICINT MEDICIN (DR MOHAMAD SAFI)CLINICINT MEDICIN (KAMAL)CLINICINT MEDICIN CLINIC ( ALI ALQAHTANI )INT MEDICIN CLINIC ( WEAAM AHMED )INT MEDICIN VCINTENSIVE CARE UNIT -ICUINTERNAL  MEDICIN CLINIC (MESHAL ALENEZI )INTERNAL MEDICINEINTERNAL MEDICINE - CONSULTANTIndustrial Check upInfectious Disease CLINICInfectious DiseasesInpatientInternal MedicineIqama Issuance and  Renewal Check upKING SALMAN HOSPITALLABORATORY - DEPARTMENTLABORATORY MAIN STORELAUNDEYLEGAL AFFAIRSLIVE QUALITY MAIN STORE W HOUSEMAXILLOFACIAL SURGERYMEDICAL DIRECTORMEDICAL RECORDS DEPARTMENTSMEDICAL REPORTSMOH DIABATIC  CLINICMOH HOSPITAL - DBAMORTUARYMaternityMedical report clinicNEONATAL INTENSIVE CARE UNIT (NICU)NEPHROLOGY CLINICNEURO MEDICALNEURO SURGERY VCNEUROLOGY CLINICNEUROLOGY CLINIC VCNEUROSURGERY CLINIC (am)NURSING HOME HEALTH CARENUTRITION CLINICNeonatal-Perinatal MedicineNephrologyNeuro-SurgeryNeurologyNeurosurgery Clinic (pm)Non electronic wheel chairNuclear MedicineOB / GYNE CLINIC - 3OB GYNE CLINICOCCUPATIONAL THERAPYOPD BLOOD EXTRACTION-FEMALEOPD BLOOD EXTRACTION-MALEOPHTHALMOLOGY CLINIC (pm)OPHTHALMOLOGY CLINIC - OROPHTHALMOLOGY CLINIC -PHCOPHTHALMOLOGY CLINIC -PHC 2OPTHA (PRE OPERATION)OPTHA SPECIALIST CLINIC-2OPTOMETRY  CLINIC 1OPTOMETRY CLINIC  FEMALEOPTOMETRY CLINIC 2OR - 5 -CS ROOMORTHO  CLINIC -2ORTHO (consultant) CLINIC (pm)ORTHO CLINIC 2 PMORTHO EMERGENCY 2ORTHOCLINIC -PHC ORTHOPEDIC CONSULTANT (AM)OSREAPROSSIS 2OSTEOPOROSIS RADIOLOGYOUTPATIENT PHARMACYObstetricsOccupational Therapy (Male)OncologyOphthalmology Clinic (pm)Ophthalmology Pre OperationOpthalmicOpticalOral/Maxillofacial SurgeryOrtho clinic 2  (Pm)OrthopedicOutpatientPATIENT RELATIONSPEDIA SCREENINGPEDIA SCREENING-PHCPEDIA SURGERYPEDIA SURGERY-PHCPEDIATIC CARDIOLOGY CLINICPEDIATIC NEUROLOGY CLINICPEDIATRIC INTENSIVE CARE UNIT -PICUPEDIATRICS  CLINC VCPEDIATRICS ( AIIAT HILAL )PEDIATRICS ( AYMAN )PEDIATRICS ( DALIA )PEDIATRICS CLINIC -1PEDIATRICS CLINIC -2PHARMACY MAIN STOREPHARMACY REFILL (FEMALE)PHARMACY REFILL (MALE)PHYSIOTHERAPY FEMALEPHYSIOTHERAPY FEMALE CLINICPHYSIOTHERAPY HOME HEALTH CAREPHYSIOTHERAPY MALEPHYSIOTHERAPY MALE CLINICPLASTIC SURGERY CLINICPOST BARIATRIC SURGERY CLINICPOST DISCHARGE CLINICPRE OPPREGNANCY CLINCPREMARITAL SCREENING CLINICPRIMARY CLINIC FOR APPPROCEDURE ROOM 1PSORIASISPSYCHIATRIC MEDICAL COMMITTEEPSYCHIATRY CLINICPSYCHIATRY CLINIC VCPSYCHIATRY CLINIC-PHCPSYCHIATRY PEDIATIC CLINICPSYCHOLOGIST CLINIC 1PSYCHOLOGIST CLINIC 2PaediatricsPalliative pain clinic Management Pediatric SurgeryPediatrics Clinic - 4Pediatrics Clinic -3PharmacyPhysiotherapyPlastic SurgeryPre-Employment Check upPre-Marital Check upPre-School Check upPreventive CarePsychiatryPulmonologyRADIOLOGY - DEPARTMENTRADIOLOGY DEPARTMENTRADIOLOGY LIBRARY **RADIOLOGY REGRDURE-FIL CLINIC APPREFIL MOBILEREFILLRL CLINICRENAL CLINICRENAL CLINIC (1)RENAL DIALYSISREPRODUCTIVE CLINICRESUSCITATION ROOMRHEUMATOLOGY - 2RHEUMATOLOGY CLINIC 1RheumatologyRheumatology Clinic 2SCREENING  CLINIC 2SCREENING CLINIC-PHC 1SCREENING PHC CLINICSOCIAL WORKER CLINICSOCIAL WORKER HOME HEALTH CARESPEECH CLINICSPEECH THERAPY (female)SPEECH THERAPY CLINICSPIROMETRY CLINICSpeech Therapy (Male)Speech Therapy / Behavioral and developmental pediatric Steam DeviceSugar Measuring DeviceTEAM HOME HEALTH CARETEST CLINICTHORACIC SURGERYUCCULTRASOUNDULTRASOUND CLINIC 1ULTRASOUND CLINIC 2URGENT CARE CLINIC 1URGENT CARE CLINIC 2UROFLOWMETRY CLINCUROLOGY (PRE OPERATION)UROLOGY CLINIC 1UROLOGY CLINIC 2UROLOGY CLINIC 3UROLOGY CLINIC VCUROLOGY CLINIC-PHCUROLOGY CLINIC-PHC (Mawed)UROLOGY CLINIC-PHC2UROLOGY ORUrologyVACCINATION COVID-19VASCULAR SURGERY CLINICVascular SurgeryWARD - C2WARD -C1WARD A1WARD B1WARD B2WARD D2WARD- A2WEAPON VALIDATION CLINICWOUND CAREYOUSEF TEST CLINICchochlear implantdentla implant dermatology consultantimplantinpatient-testob gyn clinicoccupational therapy (female)ophthalmology or ophthalmology phc 3 ophthalmology phc 4 ophthalmology phc 5ophthalmology specialist clinic 1 optometry clinic 3 optometry clinic 4optometry phc pediatric occupational therapypost op surgery clinicpppproom - 1room - 3room - 4room 5room- 2testtesttest-hussam2test-hussam_edittest1test11test2test20test3test30test4test5test6yFilterDoctorFilter by DoctorPatient TypeAllInsuranceCashAllBill TypeAllNo servicesBilledPartially BilledRefundedNot BilledAllPayer... jnhjghnb SAAUDI(The Mediterranean &amp; Gulf Cooperative Insurance &amp; Reinsurance Company (MedGulf???????????Accumed Comany123132020-NACIG - TCSACIG- MEDNETAdnicAICI captialAJHAHAL ETIHADAl Sagr Cooperative  Insurance CompanyALBAHAALFA131ALJazira TakafulALJUMAIH COallamAllianz Saudi Fransi Insurance CompanyAlrajhi Takaful for Cooperative InsuranceAMANA INSURANCEARABIA InsuranceARABIAN SHEILDArabian Shield cooperative Insurance CompanyARAMCOARAMCO ACTIVEARAMCO OTHERAXA Cooperative Insurance CompanybandrbupaBupaBUPA Arabia for Cooperative InsuranceBURUJCORP-CompanycxzcvDamanDate SeptEnvironmentETIHADfgfdgfvdgcfhgnvbGENERAL 2021GENERAL-2020-JgggGLOBEMEDGLOBEMED SAUDI ( GMS )GLOBEMED SAUDI ( GMS )GM-AMINAHGOSIGULF GENERAL - MEDNETGULF GENERAL - TCSGulf general Insurance CompanyGulf unionGulf Union Cooperative Insurance CompanytesthghgfdfdHKK Coinsurance company nameinsuranceTestIUYJUIJHAHJPJubil InsKHAMISKSAKSAKSA001KSA01KSAAMalath Cooperative Insurance &amp; Reinsurance CompanymaxmazMEDNETMNAMEMOHMOUNIRMS-NIZIHAmyNextcareOmanregrgergergrrrRTRSAGR - MEDNETSALAMA INSURANCEsaudiSaudi Arabian cooperative Insurance Company (Saico)Saudi Enaya Cooperative InsuranceSaudi United  Cooperative Insurance  (WALA&quot; , &quot;'&quot; , &quot;A)saudi1sdfsSelf Pay - CashsolidaritysosoSPSRSYTawuniya cooperative  Insurance CompanyTCStesttest2020testAL RAJHItestAL SAGR - NEXTCAREtestMalathtestMalath CooperativetestMedGulftestRAJHIAAtestSAICOtestSAUDI ENAYAtestSGH STAFF - TAWUNIYAtestTAWUNIYAtestTawuniya cooperative Insurance CompanytestWALAAtestWALAA - NEXTCAREThe Mediterranean and Gulf Cooperative Insurance and Reinsurance Company (MEDIVISA/MEDGULF)ticnToday-27-07TOKIO MARINETOTAL CARE TOTAL CARE SAUDI (TCS)TRADE UNIONUAEUCAUNSPECIFIEDyamamahyt...ClaimLineCreated ByLast Update ByDetailsew yr JJH8/*9APM-OP-000304102/11/202202/11/202202/11/202202/11/202289740.325/8184876479BLOOD BANKDr. ABDULAZIZ ALDAWSARIInsuranceBilled101|Tawuniya cooperative  Insurance Company1003373root/2022-11-01 23:31:16.247root/2022-11-01 23:31:16.247ui-button




Claim Audit#Login UserAudit DateClaim IDAction TypeAction IdentifierUpdated FieldsHIS Msg IdHIS Msg ActionHIS Msg Type
                1
            root01\11\22 23:31:161003373ADD CLAIMVISIT NO= &quot;APM-OP-0003041&quot;
                2
            root02\11\22 00:14:461003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot;
                3
            root02\11\22 00:17:311003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot; PAYER_ID=&quot;101&quot; CONTRACT_PACKAGE_NAME=&quot;&quot; MEMBER_ID=&quot;2.025&quot; PATIENT_INSURANCE_ID=&quot;54935&quot;
                4
            root02\11\22 00:17:311003373UPDATE ENCOUNTERVISIT NO= &quot;APM-OP-0003041&quot;
                5
            root02\11\22 00:24:531003373UPDATE CLAIMVISIT NO= &quot;APM-OP-0003041&quot; MEMBER_ID=&quot;789.20&quot; PATIENT_INSURANCE_ID=&quot;54937&quot;
                6
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;900280200&quot;
                7
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;1002034&quot;
                8
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;920580100&quot;
                9
            root02\11\22 00:28:281003373ADD ACTIVITYACTIVITY CODE= &quot;907640000&quot;
                10
            root02\11\22 00:36:321003373UPDATE ACTIVITYACTIVITY CODE= &quot;920580100&quot; NET_AMOUNT=&quot;528.77&quot; PATIENT_SHARE=&quot;58.75&quot; GROSS_AMOUNT=&quot;587.52&quot; DISCOUNT_AMOUNT=&quot;146.88&quot; DEDUCTIBLE_AMOUNT=&quot;0.00&quot; CO_PAYMENT_AMOUNT=&quot;58.75&quot;FP123NE&quot;))]</value>
      <webElementGuid>9dd1bbd4-e872-4012-8298-8927d9384d8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
