<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ui-button_InsuranceDetailsFormj_idt1648datalist3j_idt1652</name>
   <tag></tag>
   <elementGuidId>c4edbf2d-dc23-438a-b8cc-e47973084696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b81fe0e7-383d-4022-a9d8-6a532acf7385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652</value>
      <webElementGuid>1d5ce6d3-151a-4e0f-9f36-ce6beec0bcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5b11e382-1b55-4a98-afe1-0dc4d4aebf60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652</value>
      <webElementGuid>574399ef-5d80-4188-a8cc-c42f583c67f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,p:&quot;InsuranceDetailsForm:j_idt1648:datalist&quot;,u:&quot;InsuranceDetailsForm:j_idt1648:datalist&quot;});</value>
      <webElementGuid>1171eb90-a6e9-4bab-b94e-2d9b1d391995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652&quot;)</value>
      <webElementGuid>477d010f-5637-4869-8389-ca44e47ec315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652']</value>
      <webElementGuid>634cb20a-ec7c-4622-8f58-55cc78728188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='InsuranceDetailsForm:j_idt1648:datalist_data']/tr[4]/td/input</value>
      <webElementGuid>2d9d4c5a-bb6c-4cc1-b9ff-d2ef18056713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr[4]/td/input</value>
      <webElementGuid>3c337002-012f-4350-85af-27683aa64e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652' and @type = 'checkbox' and @name = 'InsuranceDetailsForm:j_idt1648:datalist:3:j_idt1652']</value>
      <webElementGuid>928ea4a7-3ae2-4a40-9cd3-b8e4293f7b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
