<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spouse_AccumedPatientInsuranceCreateForminsuranceLisence_filter</name>
   <tag></tag>
   <elementGuidId>d08659f1-242e-4269-85b6-506f572ce897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientInsuranceCreateForm:insuranceLisence_filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a472f022-976a-429a-b38e-831e0241adfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>4fdb96ab-79ff-409c-8e55-e42cce20ef89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:insuranceLisence_filter</value>
      <webElementGuid>8055ba31-f3a1-493a-85b4-e9542af88a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:insuranceLisence_filter</value>
      <webElementGuid>2539ee68-9f15-45b2-9dd6-233a88c87872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f138ae38-9e34-4db5-95e5-0ad9e231385d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11ab3560-1015-4d65-a9e4-604aa009cc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>453f3c24-cd44-4bea-90d4-842a242ef966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da82b8a1-ea52-45dd-b7df-5d588759607f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b64a972-86e4-4d01-8362-fc88eb4ed91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:insuranceLisence_filter&quot;)</value>
      <webElementGuid>680d69db-f3ec-4db3-8727-4f8656a3499e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientInsuranceCreateForm:insuranceLisence_filter']</value>
      <webElementGuid>977856f1-2bae-4fce-97f2-5df5f0d706a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedPatientInsuranceCreateForm:insuranceLisence_panel']/div/input</value>
      <webElementGuid>505c773a-a6bd-460e-b833-7c80a4aaccf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[95]/div/input</value>
      <webElementGuid>9c55683b-9d36-4ab3-bb4e-e075a26132fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientInsuranceCreateForm:insuranceLisence_filter' and @name = 'AccumedPatientInsuranceCreateForm:insuranceLisence_filter' and @type = 'text']</value>
      <webElementGuid>d9e2d354-d54f-4114-acc2-c92a81dbd0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
