<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spouse_AccumedPatientInsuranceCreateForminsuranceLisence_filter</name>
   <tag></tag>
   <elementGuidId>d08659f1-242e-4269-85b6-506f572ce897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientInsuranceCreateForm:insuranceLisence_filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d8c2b59-8dff-4beb-9b90-3412084d5b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>0d29e79f-ae4e-48b4-821a-901861f8aedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:insuranceLisence_filter</value>
      <webElementGuid>b4c7c7de-0443-4b84-9e74-43122368bd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:insuranceLisence_filter</value>
      <webElementGuid>632c88ed-fa4f-4a20-b7ce-23b7236e1046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bc79914-ecd1-4df2-b5b6-ceb107fa6c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f9bf86bc-2eb6-495b-9ca1-5280c2faddf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>268d9305-132d-465b-bc41-130aae1ee756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>909bcd0a-eb04-46d1-8001-74433d0e8111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>77b0913f-467b-4450-a605-15e0b26ed8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:insuranceLisence_filter&quot;)</value>
      <webElementGuid>4eb12702-188e-4c8c-80ea-fe12810ee7a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientInsuranceCreateForm:insuranceLisence_filter']</value>
      <webElementGuid>26a32d9b-f4c4-4509-aebd-72f81bce7978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedPatientInsuranceCreateForm:insuranceLisence_panel']/div/input</value>
      <webElementGuid>e64b2419-0cbe-4419-87f6-7305f4c3dfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[97]/div/input</value>
      <webElementGuid>72048dfc-f27a-4869-b9da-efcbc9d3cc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientInsuranceCreateForm:insuranceLisence_filter' and @name = 'AccumedPatientInsuranceCreateForm:insuranceLisence_filter' and @type = 'text']</value>
      <webElementGuid>8901290b-b22a-4032-bfa3-672625b5e1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
