<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Confirmed</name>
   <tag></tag>
   <elementGuidId>57a8c7f5-8157-488c-bd5c-ef05db2732f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='actionsFormInvoice:j_idt2613:j_idt2626']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>185adba2-e0c1-4e76-a35e-eb69ffca4a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>33b8e315-b91d-4f25-80ec-167bd959b55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmed</value>
      <webElementGuid>855a5d88-41a3-4deb-9c4d-b6c3761f8bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionsFormInvoice:j_idt2613:j_idt2626&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>1432f212-01bc-4044-9b59-11f3efe97913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='actionsFormInvoice:j_idt2613:j_idt2626']/span</value>
      <webElementGuid>d30cd7a9-2401-4389-8423-0f3cefbfa176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validation error, Continue!'])[1]/following::span[2]</value>
      <webElementGuid>a029d0bd-e93f-4764-a2c4-59d82dec82d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='warning'])[1]/following::span[3]</value>
      <webElementGuid>5e2f5ab5-a59b-4d0a-9f2b-c7192c4676ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[15]/preceding::span[1]</value>
      <webElementGuid>fa2b121f-01b8-4cb3-8878-e7f4eb7eb5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caudal injection of steroid'])[2]/preceding::span[2]</value>
      <webElementGuid>60dfde26-971d-4d64-8f08-0953f8924db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmed']/parent::*</value>
      <webElementGuid>d39ec377-cc88-47a7-8460-ce973afb8da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[89]/div[2]/form/button/span</value>
      <webElementGuid>45a940e2-efd8-47e1-b6e6-f5777998388a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Confirmed' or . = 'Confirmed')]</value>
      <webElementGuid>70d62f85-4fe8-44f2-bf3a-c23c286bfd46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
