<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Package_ui-icon ui-icon-triangle-1-n ui-c</name>
   <tag></tag>
   <elementGuidId>8c2ff014-0981-44cd-be49-8c207918be25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='AccumedHaadActivityListForm:activityQuantity']/a/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-spinner-button.ui-spinner-up.ui-corner-tr.ui-button.ui-widget.ui-state-default.ui-button-text-only.ui-state-hover > span.ui-button-text > span.ui-icon.ui-icon-triangle-1-n.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98d5e3f6-d472-4407-93f3-08e9c14e1b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-triangle-1-n ui-c</value>
      <webElementGuid>d148da7f-d6cf-47c2-83d5-4c141a4fa45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:activityQuantity&quot;)/a[@class=&quot;ui-spinner-button ui-spinner-up ui-corner-tr ui-button ui-widget ui-state-default ui-button-text-only ui-state-hover&quot;]/span[@class=&quot;ui-button-text&quot;]/span[@class=&quot;ui-icon ui-icon-triangle-1-n ui-c&quot;]</value>
      <webElementGuid>030f3431-b644-45ff-9fe9-80abbd1a1ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:activityQuantity']/a/span/span</value>
      <webElementGuid>74cca3d7-aa5b-4589-be4e-40f2ff1b380c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/form[2]/fieldset/div/span/table/tbody/tr[2]/td[4]/span/a/span/span</value>
      <webElementGuid>4af77593-591a-4e3b-bdd0-39d3e973ce6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
