<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_925082000</name>
   <tag></tag>
   <elementGuidId>6380d8e3-37fe-4f9f-8518-18e7be5b4551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='AccumedHaadActivityListForm:activityCode_panel']/table/tbody/tr[6]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.ui-autocomplete-item.ui-autocomplete-row.ui-widget-content.ui-corner-all.ui-state-highlight > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4ea8dffa-a796-4e20-adad-6344623ec21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>925082000</value>
      <webElementGuid>28914463-b0f9-4c91-85a5-82dd83e35b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:activityCode_panel&quot;)/table[@class=&quot;ui-autocomplete-items ui-autocomplete-table ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/tbody[1]/tr[@class=&quot;ui-autocomplete-item ui-autocomplete-row ui-widget-content ui-corner-all ui-state-highlight&quot;]/td[1]</value>
      <webElementGuid>760b9e2d-7334-4ca3-b6e7-3cb6779fb5bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:activityCode_panel']/table/tbody/tr[6]/td</value>
      <webElementGuid>a4f6cda7-e3bd-4969-bd19-8fbb1b75b431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neuraxial block, ASA 19'])[1]/following::td[1]</value>
      <webElementGuid>e3cc901a-0a2a-49d7-ba70-714effb3a3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noninvasive placement of bone growth stimulator'])[1]/following::td[3]</value>
      <webElementGuid>9a135f62-5bd2-40bc-8175-7b496488a9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neuraxial block, ASA 20'])[1]/preceding::td[1]</value>
      <webElementGuid>45703acc-c063-43cb-a870-cf51fb6ae1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neuraxial block, ASA 29'])[1]/preceding::td[3]</value>
      <webElementGuid>5be3904d-148d-46aa-b6c7-9ae2bff59cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='925082000']/parent::*</value>
      <webElementGuid>806ae4ad-669a-4934-a97a-51827d0bbbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/table/tbody/tr[6]/td</value>
      <webElementGuid>21fef89b-bd3e-4c4b-9f41-ff692c87d94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '925082000' or . = '925082000')]</value>
      <webElementGuid>12bded85-5a38-48fd-9259-72d3a9fd6019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
