<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>ecdaad12-6049-493a-adad-1340c56e5d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserRolesListForm:datalist_paginator_bottom']/span/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-paginator-page.ui-state-default.ui-corner-all.ui-state-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>efb85632-82cf-4e40-8698-1817f6d971ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-paginator-page ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>92057af4-c8d9-4c63-b6c2-df7d53d67a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>05450511-5bc0-4f8d-ae40-61059b6f46a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c7429fae-b7f2-4368-812b-70c039a1fcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Page 3</value>
      <webElementGuid>cbd77f32-e44d-443b-8f1e-1b9adf9f91c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>73b2bf95-7f08-4840-83f2-9e45556cfa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserRolesListForm:datalist_paginator_bottom&quot;)/span[@class=&quot;ui-paginator-pages&quot;]/a[@class=&quot;ui-paginator-page ui-state-default ui-corner-all ui-state-focus&quot;]</value>
      <webElementGuid>017444e7-7a65-4d26-b942-ebb08e48d5da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserRolesListForm:datalist_paginator_bottom']/span/a[3]</value>
      <webElementGuid>849db35c-2cf4-434f-bce8-226244ab01e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'3')]</value>
      <webElementGuid>386b640f-410a-4105-9333-6661cebc13ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[1]/following::a[3]</value>
      <webElementGuid>706771b8-338f-4192-b31e-f8dde0f153a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::a[4]</value>
      <webElementGuid>a79f6981-6405-4fcf-a221-2a94eeb01e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/preceding::a[2]</value>
      <webElementGuid>5dd9dcef-f11d-47b6-ac67-15a21055cf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/preceding::a[3]</value>
      <webElementGuid>9250f357-63dd-475a-b067-b00f7c0b8486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>8dd100fd-09a1-4439-aa46-ffffddce30a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[27]</value>
      <webElementGuid>30879a90-ae76-42f2-a2cb-ff1714265ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a[3]</value>
      <webElementGuid>9e294922-fb2c-4d47-9703-b1c879e9d880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '3' or . = '3')]</value>
      <webElementGuid>94250e5d-f705-4487-8962-37d930b598d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
