<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_IPApproval Dashboard</name>
   <tag></tag>
   <elementGuidId>8ae0a7db-42e8-400a-941e-6631f8a8fb30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserRolesCreateForm:pickList']/div/ul/li[57]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ui-picklist-item.ui-corner-all.ui-sortable-handle.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c53cbcfb-f4a8-4e50-8395-644b298063c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover</value>
      <webElementGuid>8f4cf3aa-3041-4dc8-bd54-52ca80a63bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-value</name>
      <type>Main</type>
      <value>1099</value>
      <webElementGuid>8418d606-549d-4ad3-99b4-39c139ab28fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-label</name>
      <type>Main</type>
      <value>IPApproval Dashboard</value>
      <webElementGuid>5c640eb3-6151-4970-ba38-b341e21066d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f815eaba-bb8c-49fa-af36-bb115653ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IPApproval Dashboard</value>
      <webElementGuid>d6e4d361-6b25-465c-a57f-9abfaf64f1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserRolesCreateForm:pickList&quot;)/div[@class=&quot;ui-picklist-list-wrapper&quot;]/ul[@class=&quot;ui-widget-content ui-picklist-list ui-picklist-source ui-corner-bottom ui-sortable&quot;]/li[@class=&quot;ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover&quot;]</value>
      <webElementGuid>bb66d8fa-ec1d-48ce-a498-63fa654ee324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserRolesCreateForm:pickList']/div/ul/li[57]</value>
      <webElementGuid>9d406ff9-a352-40d6-b552-3342efd0a9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPApproval Dashboard'])[1]/following::li[1]</value>
      <webElementGuid>2997af5e-f097-4f66-952a-db39e4f6bd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Receipts'])[3]/following::li[2]</value>
      <webElementGuid>de2dbfd9-5b6d-4743-aef6-01b66adde11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPPerforma'])[1]/preceding::li[1]</value>
      <webElementGuid>2f4c1dbd-cc2e-4e7c-b2d1-e8961b672e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Audit'])[2]/preceding::li[2]</value>
      <webElementGuid>68ef156d-3ef5-44b9-b38a-6fe142e31766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[57]</value>
      <webElementGuid>e84a5424-9c53-4a26-987f-77bba5879e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'IPApproval Dashboard' or . = 'IPApproval Dashboard')]</value>
      <webElementGuid>bec1e22b-22a9-468b-91c3-2a149b82adea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
