<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Professions</name>
   <tag></tag>
   <elementGuidId>6004058f-779c-4bbd-a949-016c44bbd99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedCliniciansViewForm:j_idt418']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ui-tabs-header.ui-state-default.ui-corner-top.ui-state-hover > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b30ad1d-34e9-422d-90fe-62339cbbde16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#AccumedCliniciansViewForm:j_idt418:j_idt423</value>
      <webElementGuid>ec9339ea-f6d1-4654-bdb3-78ca0d7aff84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c87b51b3-691c-44b1-9d63-35457fbf5f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Professions</value>
      <webElementGuid>2128a420-6cfe-4864-8339-49eec2f52fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCliniciansViewForm:j_idt418&quot;)/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-tabs-header ui-state-default ui-corner-top ui-state-hover&quot;]/a[1]</value>
      <webElementGuid>d82954a6-8868-47ef-9460-7b433df9ecad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedCliniciansViewForm:j_idt418']/ul/li[2]/a</value>
      <webElementGuid>ac3a5048-cdf3-4c5b-a713-17280f8b34b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Professions')])[3]</value>
      <webElementGuid>8806e9ed-af94-43f4-91b0-2e70a2592de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facility Categories'])[1]/following::a[1]</value>
      <webElementGuid>d7891a3e-1f3b-4f92-b7b7-f12ca43554ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regulator'])[1]/following::a[2]</value>
      <webElementGuid>d89bfe12-9975-43e5-a5a4-7e2a561678b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Pathology'])[3]/preceding::a[1]</value>
      <webElementGuid>95270110-d3b4-4f12-8d4c-485958fbacf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ear, nose and throat (ENT)'])[3]/preceding::a[1]</value>
      <webElementGuid>4ca7f486-4e52-4fab-8ab6-7a49d9cf1859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#AccumedCliniciansViewForm:j_idt418:j_idt423')]</value>
      <webElementGuid>e9672534-e3a3-47f1-9a10-4858e8b250f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/ul/li[2]/a</value>
      <webElementGuid>f9ba77ab-af24-4bc0-a429-2281e2ce0f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#AccumedCliniciansViewForm:j_idt418:j_idt423' and (text() = 'Professions' or . = 'Professions')]</value>
      <webElementGuid>50f17702-fc40-4087-adb5-9a1ed8cef35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
