<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_save</name>
   <tag></tag>
   <elementGuidId>40376a05-ef64-462b-b561-15adf344183e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;AccumedCliniciansCreateForm:j_idt309&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>946c1cd7-1b00-42c4-85b5-f8c586e6b592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1667461107165</value>
      <webElementGuid>20c4fe32-f38d-4df9-abd2-fd0bf3df9986</webElementGuid>
   </webElementProperties>
</WebElementEntity>
