<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by Name_AccumedCliniciansListF_0e5895</name>
   <tag></tag>
   <elementGuidId>1a486790-73a6-4bb5-80f9-a1f2a2168aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedCliniciansListForm:datalist:j_idt185:filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c1cce35-0e45-4470-b60c-ef7b2c603dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedCliniciansListForm:datalist:j_idt185:filter</value>
      <webElementGuid>67281c03-2177-4392-8da3-73aea49af913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedCliniciansListForm:datalist:j_idt185:filter</value>
      <webElementGuid>99fb3aad-1357-43a5-8589-9200542261a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>90cbf6c8-89d5-43f9-a27f-ad8edd85b533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b50ab6b3-8aa8-4bc4-99e0-ae98b3485440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>AccumedCliniciansListForm:datalist:j_idt185:filter_label</value>
      <webElementGuid>aabe73f6-6daa-4171-8a31-fc7f19dffae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>acd720f3-ee5d-4343-ac67-fd5a6d4671a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2af2fa94-e9ba-4070-b00e-9f2c79d1062f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb5f31a7-0735-447e-859e-880fd607070b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCliniciansListForm:datalist:j_idt185:filter&quot;)</value>
      <webElementGuid>e85b2f47-2186-4b8e-a35e-cd620b0f0186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedCliniciansListForm:datalist:j_idt185:filter']</value>
      <webElementGuid>e956a665-1fc2-4287-b244-647606b18448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='AccumedCliniciansListForm:datalist:j_idt185']/input</value>
      <webElementGuid>ca90eaa8-d82c-442a-8195-0f56e7fbc438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/input</value>
      <webElementGuid>15d7c48e-b9ac-4c16-871f-d5e8b2890982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedCliniciansListForm:datalist:j_idt185:filter' and @name = 'AccumedCliniciansListForm:datalist:j_idt185:filter']</value>
      <webElementGuid>918287ce-3868-4709-a6d6-c81b2dbd1fd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
