<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by Profession_AccumedClinician_99dd7f</name>
   <tag></tag>
   <elementGuidId>5084f0ed-06b9-472d-b9c1-f9036a1973c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0e8fa99-7312-448a-b41b-7ffe0d25e2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter</value>
      <webElementGuid>f3f1cc17-5493-44ba-ac22-83c49d083f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter</value>
      <webElementGuid>9e93d40a-d88c-4752-aa17-603e1628a308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>41d811cc-1aa6-4338-9c54-9eab013db4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5917747b-c93d-4cc2-832f-ceba22e8ff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter_label</value>
      <webElementGuid>1856ce69-0609-4f4c-8e44-9d66beeddc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d03c04dc-05e9-4037-b8d2-90d3224e92b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11174d06-f9e3-4ed6-a092-0950c80bbeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75959a7c-cfe6-411e-89c5-d73285ece6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter&quot;)</value>
      <webElementGuid>5cee0df6-a385-4f4d-9227-78b939a4fd9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter']</value>
      <webElementGuid>ef53d937-d3ab-4bfd-a23c-234da8208c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430']/input</value>
      <webElementGuid>32a54e45-a6e5-4aaf-bb34-c46847cf5e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/table/thead/tr/th[2]/input</value>
      <webElementGuid>58faa4df-e479-459f-b0ea-5ee90879e3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter' and @name = 'AccumedClinicianProfessionsCreateForm:checkboxDT:j_idt430:filter']</value>
      <webElementGuid>d75b3905-2e87-4866-8dcc-44b80b33be6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
