<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CREDIT_CARD</name>
   <tag></tag>
   <elementGuidId>3d3ba77d-0a85-4b8e-9d8c-cb54c0860749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='finAccountsSetupForm:accountTypeId_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87fc084f-3217-49ca-9fc5-dbe9faa125ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>947f6c21-8d59-4949-89f5-b94d366d223d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>CREDIT_CARD</value>
      <webElementGuid>ffbae6d6-04df-4c59-92b9-7083ce8a71ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a6756f2f-bacc-4040-8612-cb416608549a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7d6d7965-5769-4d05-a039-9ed47b1fdecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>finAccountsSetupForm:accountTypeId_2</value>
      <webElementGuid>9314e388-0109-43dd-b72e-2d55cf4b9beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CREDIT_CARD</value>
      <webElementGuid>831c8c75-1c9b-4a8c-9a29-07d05b530d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;finAccountsSetupForm:accountTypeId_2&quot;)</value>
      <webElementGuid>2c8e1efd-176e-4022-b386-cb46b5abc93e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='finAccountsSetupForm:accountTypeId_2']</value>
      <webElementGuid>e019403d-3f50-4766-8ecc-db696d4cc3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='finAccountsSetupForm:accountTypeId_items']/li[3]</value>
      <webElementGuid>7cc665fa-793f-4cb5-b7a5-129272d16ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASH'])[6]/following::li[1]</value>
      <webElementGuid>e11938d3-4cb3-4753-a69c-410913f8ca0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANK_ACCOUNT'])[4]/following::li[2]</value>
      <webElementGuid>bbc431f1-e82c-4fcd-8a7a-dc43e7193a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEBIT_CARD'])[4]/preceding::li[1]</value>
      <webElementGuid>cbc5228a-92df-4793-a3f1-8216a8c448bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISCOUNT'])[4]/preceding::li[2]</value>
      <webElementGuid>b900a589-136a-4a51-a502-56849a8897fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/ul/li[3]</value>
      <webElementGuid>e1163f8f-f9d1-4306-aa2c-db42dd17d6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'finAccountsSetupForm:accountTypeId_2' and (text() = 'CREDIT_CARD' or . = 'CREDIT_CARD')]</value>
      <webElementGuid>ff673654-4e8f-41a3-b718-50f2f4fa1886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
