<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Clinicians was successfully deleted</name>
   <tag></tag>
   <elementGuidId>43ff59d0-5f83-4764-941a-d6462791a3e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedCliniciansListForm:ImportMessages_container']/div/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-growl-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>471fb9d2-01f6-4906-b107-e4a5d4c864a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-growl-title</value>
      <webElementGuid>79aa3bb0-9526-4878-865b-603d672e05c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinicians was successfully deleted.</value>
      <webElementGuid>b1873cd3-40f9-4ca5-92df-258d7ff7f459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedCliniciansListForm:ImportMessages_container&quot;)/div[@class=&quot;ui-growl-item-container ui-state-highlight ui-corner-all ui-helper-hidden ui-shadow ui-growl-info&quot;]/div[@class=&quot;ui-growl-item&quot;]/div[@class=&quot;ui-growl-message&quot;]/span[@class=&quot;ui-growl-title&quot;]</value>
      <webElementGuid>c2c5e25b-68dc-4d6d-926e-10d3df4cbc4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedCliniciansListForm:ImportMessages_container']/div/div/div[2]/span</value>
      <webElementGuid>8a5da752-5af1-4986-a0c6-bd33daef3328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Clinicians'])[1]/following::span[2]</value>
      <webElementGuid>9c8452d4-bcbe-4087-a09b-a170c79e0cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validating Clinicians ,please wait...'])[1]/following::span[3]</value>
      <webElementGuid>7848cfbe-40d7-4d74-9457-9fb099cdae0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/preceding::span[1]</value>
      <webElementGuid>fad01029-ef0b-4745-a799-f40d026c524c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure?'])[1]/preceding::span[4]</value>
      <webElementGuid>953e891d-e634-42d4-b8e7-f7f311ec1a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clinicians was successfully deleted.']/parent::*</value>
      <webElementGuid>1cd51638-a117-4eab-b589-60bdfad256dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/span</value>
      <webElementGuid>1690ebd5-2b44-4e4e-a027-437b6894ba58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Clinicians was successfully deleted.' or . = 'Clinicians was successfully deleted.')]</value>
      <webElementGuid>5e2174f4-0532-4319-bff6-05a61c7c3b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
