<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_23</name>
   <tag></tag>
   <elementGuidId>ff546cf3-0830-4985-b7ce-e6c061541c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/table/tbody/tr[4]/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-state-default.ui-state-active.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d86466d-ca19-4e5d-9084-67729423817d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-state-default ui-state-active ui-state-hover</value>
      <webElementGuid>de22bce3-c6ad-49e3-94c0-c0943d430d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>74b16e15-4948-4996-a57f-41e066d1f3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>431d6325-d5f1-4ba2-afbd-557c19a2cfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/table[@class=&quot;ui-datepicker-calendar&quot;]/tbody[1]/tr[4]/td[@class=&quot;ui-datepicker-days-cell-over  ui-datepicker-current-day&quot;]/a[@class=&quot;ui-state-default ui-state-active ui-state-hover&quot;]</value>
      <webElementGuid>043051f8-9645-48c2-9aac-958245de9369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/table/tbody/tr[4]/td[5]/a</value>
      <webElementGuid>49242ab3-ccae-4270-ab3c-0f0ca3795cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'23')]</value>
      <webElementGuid>88870b73-7697-40e6-ba3d-c31edf0e463b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::a[23]</value>
      <webElementGuid>dea0493f-83b0-4069-9ac2-2ed2733e2242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::a[23]</value>
      <webElementGuid>021d112a-9ce9-46a8-9ec3-9e4e2cac5f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::a[10]</value>
      <webElementGuid>8dc9ce11-9194-48dd-a153-e378739b826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[10]</value>
      <webElementGuid>c94cd71d-ac60-4924-aee6-c9e9d4365bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23']/parent::*</value>
      <webElementGuid>8e832288-258b-4d89-a144-d4f7470ad859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[61]</value>
      <webElementGuid>ef96a647-26b4-45be-816f-87ec8ebe223a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/a</value>
      <webElementGuid>905a13ee-a29f-4f90-ac40-bc33a795a718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '23' or . = '23')]</value>
      <webElementGuid>a502b804-e9dd-42d6-9157-f67a5b2da130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
