<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error MessagePatient is exist with the _18db68</name>
   <tag></tag>
   <elementGuidId>8d18b44b-398a-426f-b449-c70b9fcf6987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='growl_container']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-growl-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f1f32ff-e031-440a-b87a-1ac4d80b7ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-growl-item</value>
      <webElementGuid>31ad23ec-b82a-45c7-92fe-0208062dd4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error MessagePatient is exist with the same national id !</value>
      <webElementGuid>3449ef33-cb67-47eb-994e-d28e3ddd604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;growl_container&quot;)/div[@class=&quot;ui-growl-item-container ui-state-highlight ui-corner-all ui-helper-hidden ui-shadow ui-growl-error&quot;]/div[@class=&quot;ui-growl-item&quot;]</value>
      <webElementGuid>886a737a-a611-4f0e-9af9-dc1ebb4ce0d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='growl_container']/div/div</value>
      <webElementGuid>d2dd654a-c39a-4bf2-a870-5509ac5742b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records found.'])[1]/following::div[16]</value>
      <webElementGuid>1044fa83-daf1-4e61-ab9a-94b4690bc0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIS Msg Type'])[2]/following::div[17]</value>
      <webElementGuid>bb44089a-be09-43fe-ad24-986233bc2518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::div[4]</value>
      <webElementGuid>712eec90-b691-4a52-b4b9-00090e5b6650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div</value>
      <webElementGuid>b07bb3ed-19b9-4370-95d6-62e083370b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Error MessagePatient is exist with the same national id !' or . = 'Error MessagePatient is exist with the same national id !')]</value>
      <webElementGuid>a65e911f-8e67-4543-9467-7346d6bebfa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
