<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by National ID_patientFormpati_ba79b9</name>
   <tag></tag>
   <elementGuidId>ac1384a9-d367-4cc0-99be-cc22457e63bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patientForm:patientTbl:j_idt177:filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e02741b1-28a9-4f2e-a9a7-3bd319c8268d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patientForm:patientTbl:j_idt177:filter</value>
      <webElementGuid>5436ad19-3408-41e3-9d62-1c550a929791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patientForm:patientTbl:j_idt177:filter</value>
      <webElementGuid>04565063-6de6-43fe-a42a-4371f3ff01cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>750c18c5-2940-4abd-b8d9-30f10001a3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d3327dc7-9de9-4f16-a42f-416cf91fe4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>patientForm:patientTbl:j_idt177:filter_label</value>
      <webElementGuid>bea1daeb-3cac-482f-b675-11d391a01032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d616f9e3-dd7d-44d6-b873-d1207bbf6d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f27073af-6112-4bc2-9198-6ca5c9b6d544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a5e8fca-66f1-4267-8e52-ae4d752a3af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientForm:patientTbl:j_idt177:filter&quot;)</value>
      <webElementGuid>dffa2833-94e2-407e-9567-4c6a22e09f76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patientForm:patientTbl:j_idt177:filter']</value>
      <webElementGuid>c9303888-d40c-4a3c-80d9-734d8982c0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='patientForm:patientTbl:j_idt177']/input</value>
      <webElementGuid>8cd3a9df-1602-43a2-b16d-ad722f8f3520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>22972e25-63f6-4b61-98f3-9464501c6ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'patientForm:patientTbl:j_idt177:filter' and @name = 'patientForm:patientTbl:j_idt177:filter']</value>
      <webElementGuid>af095570-cd2a-4be4-ba43-1e9e331b5aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
