<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AccumedPatientCreateFormpatientSurname</name>
   <tag></tag>
   <elementGuidId>33af1c13-eb72-48ed-8be3-4ae7ad77492f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientCreateForm:patientSurname']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5abe3370-8d89-4ff7-95c8-f7d2a2703750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:patientSurname</value>
      <webElementGuid>e6f27af6-b0fb-48df-8ac8-a3b0902b1686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:patientSurname</value>
      <webElementGuid>57edd346-af62-4165-b633-06dcb767223e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1410d8e8-f513-4931-91a3-a2ff2aae4974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>b15efa65-044b-478f-88c5-601de5252dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>90ab8aff-6886-4e99-b3b8-2a8fdf666f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd976c63-da0c-4faf-8553-c12111bdf993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>abc538e4-c241-40d7-b5c0-4bf13824ca08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientCreateForm:patientSurname&quot;)</value>
      <webElementGuid>63bbc129-127b-4351-b11c-558d7154b162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientCreateForm:patientSurname']</value>
      <webElementGuid>56f92914-4f1c-480e-b994-bf364b2a0b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientCreateForm:j_idt304']/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>4e4f71e0-526f-46b4-a7bc-02a0ec9e69d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>0224353c-9b99-4648-9328-672ae790d641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientCreateForm:patientSurname' and @name = 'AccumedPatientCreateForm:patientSurname' and @type = 'text']</value>
      <webElementGuid>dbde1ece-1684-4da9-a432-c4f2600efd7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
