<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tawuniya cooperative  Insurance Company</name>
   <tag></tag>
   <elementGuidId>ef050da0-4c3d-4747-9b88-3c3dfd144ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='phWLForm:payer_autoFilter_101']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9c969d63-2081-4d07-b0ee-5191d32d35f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>526552e3-b6fd-4f73-97d7-bafedb90e520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Tawuniya cooperative  Insurance Company</value>
      <webElementGuid>c76a5b22-f057-4246-87ac-e25123d9fe49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>96323c50-449b-4275-92bf-a85d01d66074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>467aa167-dbc2-464a-822e-e0dbd50ea4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:payer_autoFilter_101</value>
      <webElementGuid>79a87d7a-1e01-4174-9661-e6d55ac64e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tawuniya cooperative  Insurance Company</value>
      <webElementGuid>cb68fd67-9c46-430d-8de4-67b3d59d1c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:payer_autoFilter_101&quot;)</value>
      <webElementGuid>a29f1d10-33c2-4493-95fd-8403331c0fd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='phWLForm:payer_autoFilter_101']</value>
      <webElementGuid>ef3c1abe-f6ff-42bb-8080-b46db679b886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='phWLForm:payer_autoFilter_items']/li[102]</value>
      <webElementGuid>74cd952c-3c29-4b81-b481-1f5731b2fb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SY'])[2]/following::li[1]</value>
      <webElementGuid>d0822fbe-4286-4cb8-9b73-583d36c82739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SR'])[2]/following::li[2]</value>
      <webElementGuid>b81d6d86-20b4-4cd9-9953-6bea0a3a22b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TCS'])[2]/preceding::li[1]</value>
      <webElementGuid>e1f07dee-cd91-454f-8874-4f659dde382e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[2]/preceding::li[2]</value>
      <webElementGuid>1832af4f-a239-4e50-8401-8bc477e39568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[102]</value>
      <webElementGuid>a2a3384c-24a7-48a4-8174-58e128e41410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'phWLForm:payer_autoFilter_101' and (text() = 'Tawuniya cooperative  Insurance Company' or . = 'Tawuniya cooperative  Insurance Company')]</value>
      <webElementGuid>1d740d51-0ef6-4325-8239-00c79d94f2d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
