<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Patient_advanceCollectionDlgFo_160f63</name>
   <tag></tag>
   <elementGuidId>6f69fc66-fa99-45d5-a2a7-b859e243ad48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advanceCollectionDlgForm:patient_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53ee3c50-ed16-46d9-bfa5-d10846b646f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advanceCollectionDlgForm:patient_input</value>
      <webElementGuid>41c836bf-df27-468e-baf9-aeedee69201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advanceCollectionDlgForm:patient_input</value>
      <webElementGuid>a06b95e0-de1e-4206-9e6e-f592f0bf4ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c176eadb-2968-48d2-844b-4be7b6884312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>2e8b28ed-9c0f-4354-a852-c9389386f2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e6de7626-c727-4128-ab3d-8a56bb11975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by Mrn ,National ID, Name and Phone Number.</value>
      <webElementGuid>0c5804ce-b950-40c4-adf4-8a7beb81071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>90273e7b-04b9-4e9d-8316-907464da9f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search by Mrn ,National ID, Name and Phone Number.</value>
      <webElementGuid>ed56d2dc-ecd3-4a10-bbd5-400e7cccf4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>56bf268b-15d9-42c8-a25f-908cb0956667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2107684b-f61b-4bf4-8246-a4461de969fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e96cad54-e063-4548-bf1d-2a611924d761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>59d43b5f-f789-441e-b3c4-3c98f8663315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanceCollectionDlgForm:patient_input&quot;)</value>
      <webElementGuid>8b2b2668-ef54-4d74-9caf-2390d30a7e3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advanceCollectionDlgForm:patient_input']</value>
      <webElementGuid>37605c63-f3ff-469f-aeae-914ba9bbbf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='advanceCollectionDlgForm:patient']/input</value>
      <webElementGuid>8cfc9fd7-ef11-4dd9-a354-fd382fed2fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/table/tbody/tr/td/table/tbody/tr/td/span/input</value>
      <webElementGuid>c17e891b-d44c-4353-934c-208ef0c0cadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advanceCollectionDlgForm:patient_input' and @name = 'advanceCollectionDlgForm:patient_input' and @type = 'text' and @placeholder = 'Search by Mrn ,National ID, Name and Phone Number.' and @title = 'Search by Mrn ,National ID, Name and Phone Number.']</value>
      <webElementGuid>182bf43a-c613-4a24-9829-5df0da9e83fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
