<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hide</name>
   <tag></tag>
   <elementGuidId>637dcc94-b69f-4c47-8500-073b3785c00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advanceWithDrowsDlgForm:j_idt340']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e4f0788-3b53-42be-9b6f-e2d31b78ceb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>7f822768-aa7f-4296-8227-92355178185c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>95780da4-6c59-48d2-8d19-6c7ad91bc776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanceWithDrowsDlgForm:j_idt340&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>33e14dc5-5f14-41d1-891c-666474ebdc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='advanceWithDrowsDlgForm:j_idt340']/span</value>
      <webElementGuid>c5e90604-86be-49d8-a849-874a81b2242b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[2]/following::span[1]</value>
      <webElementGuid>6f8a93dc-08e9-4991-8019-c5ec606db774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[2]/following::span[2]</value>
      <webElementGuid>41fb854f-45a9-4bf5-b681-be8808990993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National ID'])[3]/preceding::span[2]</value>
      <webElementGuid>04a6b215-b255-4efb-bf67-6e3cbf7a5d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient'])[3]/preceding::span[2]</value>
      <webElementGuid>ba21c551-f77d-48ae-b2a8-9b2e6c64d960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hide']/parent::*</value>
      <webElementGuid>eae8e9dc-3316-46c1-aee6-425db077ba9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/form/table/tbody/tr/td/button/span</value>
      <webElementGuid>eb24648b-c376-4995-a421-289cda572ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hide' or . = 'Hide')]</value>
      <webElementGuid>4001cd5c-e48e-447e-840d-ae30c005306d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
