<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Print</name>
   <tag></tag>
   <elementGuidId>1eb8eca2-100a-4a94-846a-7c1fe263de02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='claimBillsForm:payment:0:printInvoiceBTN']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7cd1f05-5871-4943-8f64-e91362a4ffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>91b11398-de8e-4c83-893b-8e5c5f3c5977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>f20e6dd3-11e8-4040-bff1-f82ea7f42180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;claimBillsForm:payment:0:printInvoiceBTN&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>96b03bf1-8d5c-42ef-805c-6918488961e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='claimBillsForm:payment:0:printInvoiceBTN']/span[2]</value>
      <webElementGuid>1f2c918a-16ec-4ede-91c2-f4bce896a694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='root/'])[1]/following::span[3]</value>
      <webElementGuid>111bc8e4-fa4f-4eda-a10d-fd8cbdbdaf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash'])[1]/following::span[4]</value>
      <webElementGuid>1b1311d1-4f18-4258-94bb-7b4831faabf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::span[2]</value>
      <webElementGuid>59fba9dd-8fe1-4ccb-972b-c5a116c9591f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[1]/preceding::span[4]</value>
      <webElementGuid>57add43c-ffde-4f60-a314-1a43122773f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print']/parent::*</value>
      <webElementGuid>f289e6de-9536-4df2-9b3b-f9ba0cdd4946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[19]/button/span[2]</value>
      <webElementGuid>249f333a-c41f-4991-8b03-91fe142c4c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Print' or . = 'Print')]</value>
      <webElementGuid>32caa457-bacc-4cbb-b68b-04a38f44a58e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
