<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Preview</name>
   <tag></tag>
   <elementGuidId>e14c9a7c-76c4-4c2b-a5d6-5727d2e5558c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headerForm:waitingCollectionSettlementListView:1:viewInvoice2']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36653c50-c503-4840-85f0-0d6f8fb1f5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>afd7d8e7-a802-473f-bca4-4832885ee4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>3469adf7-0f88-4bdc-8f52-00de4bfe18cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerForm:waitingCollectionSettlementListView:1:viewInvoice2&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>25dc8c78-3202-4a91-9b08-2177961e3f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headerForm:waitingCollectionSettlementListView:1:viewInvoice2']/span[2]</value>
      <webElementGuid>076af669-34e8-404b-b3ec-184f843347fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[2]/following::span[2]</value>
      <webElementGuid>0200021c-b3cc-4595-b692-efb16ce2c14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting'])[1]/following::span[3]</value>
      <webElementGuid>8b1e296f-10f3-480c-a503-8fdd22680e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='root'])[3]/preceding::span[3]</value>
      <webElementGuid>8eb710d8-0d15-4256-808e-97072f3a1455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reception'])[3]/preceding::span[3]</value>
      <webElementGuid>a936c922-f275-4124-8889-a05498eb0fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[14]/button/span[2]</value>
      <webElementGuid>fdc91b7c-689a-47fa-a948-0730b954d695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Preview' or . = 'Preview')]</value>
      <webElementGuid>fa7bb6b9-2112-4e73-b3a9-bf6381965b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
