<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Required_AccumedHaadActivityListIPFormdatalist3valorTotalItem</name>
   <tag></tag>
   <elementGuidId>d0b5749e-d509-4617-a9ac-dad28b72876a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListIPForm:datalist:3:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b7eba75-65a8-4bed-b9c8-0215e85bb914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:3:valorTotalItem</value>
      <webElementGuid>7bffc17a-2d50-4d7a-b327-ee271f84d9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:3:valorTotalItem</value>
      <webElementGuid>b086b20b-e174-416a-a5f5-5bdb6e72ed74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8f32cea-a4c8-42d2-85b8-6378e9879da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListIPForm:datalist:3:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListIPForm:datalist:3:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListIPForm:datalist&quot;});</value>
      <webElementGuid>9f8c269a-245b-445a-a406-27e540373632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>14fa01ae-84a1-4bd2-ac21-8a38bafb0f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>438f6b4f-e403-4c0e-bb9a-09eca0ce1084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c55bbe05-916a-4432-b4e9-6f0967844409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a402302-d72a-4df0-af78-ecb2ede5d53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListIPForm:datalist:3:valorTotalItem&quot;)</value>
      <webElementGuid>72131c57-95f0-49a1-871b-2f013ea7f58c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListIPForm:datalist:3:valorTotalItem']</value>
      <webElementGuid>c618b91d-6f9c-427a-bd18-a242286219ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListIPForm:datalist_data']/tr[4]/td[21]/input</value>
      <webElementGuid>7d758b02-86f2-428a-9af5-56ca2a3ac58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[21]/input</value>
      <webElementGuid>6ff44d59-52d7-4fa8-9cd4-2b9b6b25997b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListIPForm:datalist:3:valorTotalItem' and @name = 'AccumedHaadActivityListIPForm:datalist:3:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>f930729f-2c7b-4a8f-9bb5-b8615e911178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
