<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Required_AccumedHaadActivity_3b6fa6</name>
   <tag></tag>
   <elementGuidId>cf95c0a7-c828-4af9-a1a6-cd066f4c0b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListIPForm:datalist:0:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>684727e5-04d7-4b6b-a60e-383ad3765eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:0:valorTotalItem</value>
      <webElementGuid>22f66001-e9b7-4609-9c00-d5512477715d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:0:valorTotalItem</value>
      <webElementGuid>3751b2d4-433c-460d-abc1-c5983854515f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b55e868a-516d-43ac-b0af-8d0bc053b862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListIPForm:datalist:0:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListIPForm:datalist:0:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListIPForm:datalist&quot;});</value>
      <webElementGuid>5b214289-a271-4ed0-870e-0f4175e71246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>2f134c18-add1-45f7-9d84-aaa164600ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9c9ab0a3-e244-4227-8842-5f063e046dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c19cebb-a9b9-47f0-ada8-d147bccf9bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5efbd9af-0454-4eba-bb96-abdda202ba95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListIPForm:datalist:0:valorTotalItem&quot;)</value>
      <webElementGuid>7860fd51-737b-4803-a6ce-5be014c07c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListIPForm:datalist:0:valorTotalItem']</value>
      <webElementGuid>597a25dc-e69b-4020-8b74-ef8985eedeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListIPForm:datalist_data']/tr/td[21]/input</value>
      <webElementGuid>28493bab-5438-4503-9e18-55ddf35c4338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[21]/input</value>
      <webElementGuid>8cbe299e-2e66-4960-8108-f3cd41b0bff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListIPForm:datalist:0:valorTotalItem' and @name = 'AccumedHaadActivityListIPForm:datalist:0:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>71052c10-cbf3-45d3-bd92-e7837d738ae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
