<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Required_AccumedHaadActivity_e488c9</name>
   <tag></tag>
   <elementGuidId>1d7ddceb-adb5-4412-8e2a-b150c0f14781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListIPForm:datalist:3:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21b8174a-f4ea-4768-9a86-546b1651ae08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:3:valorTotalItem</value>
      <webElementGuid>d73c858a-d991-44b8-9f07-dfe3b5135055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:3:valorTotalItem</value>
      <webElementGuid>c55d3a70-3ae6-4e6c-98da-7d2c4e16d6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64b8c2d4-fc3f-4c4d-befc-ea780900341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListIPForm:datalist:3:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListIPForm:datalist:3:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListIPForm:datalist&quot;});</value>
      <webElementGuid>6c0aaad9-26d7-45c2-9e36-ab4f5d6ef1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>4b6c08a0-fbb4-49a8-9ab9-e72dc043cdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c4f2460a-80b3-4013-801b-a2ff78aa4503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9981e522-ea4e-4d77-a63c-ecaeec0d298d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34423336-5d55-486d-aafe-41c33be1de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListIPForm:datalist:3:valorTotalItem&quot;)</value>
      <webElementGuid>482a6842-f778-47f9-95b7-78b022d87ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListIPForm:datalist:3:valorTotalItem']</value>
      <webElementGuid>d6ebd61d-e1f4-41d7-a472-107f62441238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListIPForm:datalist_data']/tr[4]/td[21]/input</value>
      <webElementGuid>4ea25d3e-abb1-4ed6-a787-f96c84392b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[21]/input</value>
      <webElementGuid>c322b0a8-cf01-4539-85a5-1d51b1d4913a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListIPForm:datalist:3:valorTotalItem' and @name = 'AccumedHaadActivityListIPForm:datalist:3:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>979be4b3-746e-4823-9f84-10a82c90f903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
