<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Required_AccumedHaadActivity_416322</name>
   <tag></tag>
   <elementGuidId>146b2c1c-a113-48f1-9e63-bede019f8915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListIPForm:datalist:2:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65e11ad8-59ac-46ab-849d-4023c0e3dd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:2:valorTotalItem</value>
      <webElementGuid>2bf322dc-46c0-4e94-8899-76c8c2205c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:2:valorTotalItem</value>
      <webElementGuid>d845fdab-7541-4dcb-98ad-3ba8f9324059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97f8d926-d69b-49fb-9df6-db4bf3f0c9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListIPForm:datalist:2:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListIPForm:datalist:2:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListIPForm:datalist&quot;});</value>
      <webElementGuid>ea9a3266-8495-4d54-be24-9d0c83347304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>2e214ea7-ee46-490f-8423-fdbe036a2c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>178caef1-50aa-4b42-ac11-6528a623f3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca8facdd-9a66-452b-b6ba-e8d3e653c348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b5d0244-f659-4052-af54-cdc0d289ee0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListIPForm:datalist:2:valorTotalItem&quot;)</value>
      <webElementGuid>9e8271f7-0670-4ef7-b877-75ee4a4a9259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListIPForm:datalist:2:valorTotalItem']</value>
      <webElementGuid>bd3c9d0e-2aea-4967-b933-a2a9c513d4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListIPForm:datalist_data']/tr[3]/td[21]/input</value>
      <webElementGuid>0e637cf5-c5c4-4f2d-9dba-8a7e3f624516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[21]/input</value>
      <webElementGuid>f6634ba8-65a2-4f32-9818-784caaeda323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListIPForm:datalist:2:valorTotalItem' and @name = 'AccumedHaadActivityListIPForm:datalist:2:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>5aa478b8-6720-457d-96c6-e29c65b4dd3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
