<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval Required_AccumedHaadActivityListIPFormdatalist6valorTotalItem</name>
   <tag></tag>
   <elementGuidId>c26e95a0-28e3-4857-a735-b76f76f70eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListIPForm:datalist:6:valorTotalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45b66475-1785-42ed-a82e-121dc8b90d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:6:valorTotalItem</value>
      <webElementGuid>31cca66b-e31f-4b24-a784-f6cc54f7ebe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListIPForm:datalist:6:valorTotalItem</value>
      <webElementGuid>3569481b-d61c-4288-92f8-c44fff562bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba8ab664-160d-475b-aa7e-f4d9eacbf98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListIPForm:datalist:6:valorTotalItem&quot;,e:&quot;valueChange&quot;,p:&quot;AccumedHaadActivityListIPForm:datalist:6:valorTotalItem&quot;,u:&quot;AccumedHaadActivityListIPForm:datalist&quot;});</value>
      <webElementGuid>036c5243-cffb-4c35-bc33-0cce42399392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>c13db9d9-0efb-4180-8fd6-d04586ccf19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>aea024c2-35de-4f55-8e7c-1c8d583c0b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85151bf5-e512-437c-a50f-b9c12efbe51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9244948b-2458-4786-a0d6-5d3cfa6aae2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListIPForm:datalist:6:valorTotalItem&quot;)</value>
      <webElementGuid>a5d9a0de-e7f9-43d8-8608-072813eebe66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListIPForm:datalist:6:valorTotalItem']</value>
      <webElementGuid>52af5d6f-1209-4054-8b82-1d3c39ec5b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='AccumedHaadActivityListIPForm:datalist_data']/tr[7]/td[21]/input</value>
      <webElementGuid>6af3358e-b243-400d-a57b-914f866eb137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[21]/input</value>
      <webElementGuid>fb3d9efa-a5a6-417c-9af4-375348cbaa84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListIPForm:datalist:6:valorTotalItem' and @name = 'AccumedHaadActivityListIPForm:datalist:6:valorTotalItem' and @type = 'text']</value>
      <webElementGuid>72f9d269-53ac-4263-bd00-fb409e97ac1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
