<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_OK_firstC</name>
   <tag></tag>
   <elementGuidId>bfe45a69-ddd3-4fff-820d-8521657f1600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='alerForm']/table[2]/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>44b3ff1c-c3ce-4154-b6b4-cc1ab2950def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstC</value>
      <webElementGuid>97042c16-2a49-48ab-b3c6-07b6950f1dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alerForm&quot;)/table[2]/tbody[1]/tr[1]/td[@class=&quot;firstC&quot;]</value>
      <webElementGuid>6a050a21-4ccb-4490-bf68-e2b0bf9e1719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='alerForm']/table[2]/tbody/tr/td[3]</value>
      <webElementGuid>abf061c2-0847-492d-ab93-c400672f8103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[3]</value>
      <webElementGuid>8d6fd7a2-1546-43af-8e29-8eca151b81fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
