<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dental_ui-button-icon-left ui-icon ui-c ui-icon-circle-close</name>
   <tag></tag>
   <elementGuidId>4b4940d0-491d-4c6d-8e1f-a1738729b08a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='PackageDetailsListForm:j_idt2382']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2da63f9c-065e-47e0-a44b-03f792e60e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c ui-icon-circle-close</value>
      <webElementGuid>9c92a89e-2142-4093-b3b5-c4252107ac0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PackageDetailsListForm:j_idt2382&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c ui-icon-circle-close&quot;]</value>
      <webElementGuid>f98169e0-fe96-4da3-b1ca-dc3c558cf4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='PackageDetailsListForm:j_idt2382']/span</value>
      <webElementGuid>5f21be6a-5940-455f-bd4a-ba9b287c3aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/div[2]/form/div/div/button/span</value>
      <webElementGuid>2d82dd90-7f4e-47b7-a868-47ce516c2e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
