<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit AccumedFacilityUserRoles_ui-icon _39cbf9</name>
   <tag></tag>
   <elementGuidId>c223123f-97ac-416b-bc1d-0d42dfeb623a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ui-dialog-titlebar-icon.ui-dialog-titlebar-close.ui-corner-all.ui-state-hover.ui-state-focus > span.ui-icon.ui-icon-closethick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserRolesEditDlg']/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13f5b3a1-ef17-4c77-94c6-d32cb012d4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-closethick</value>
      <webElementGuid>c9a95bf3-7279-44b5-97b6-ee916f9fc5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserRolesEditDlg&quot;)/div[@class=&quot;ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top ui-draggable-handle&quot;]/a[@class=&quot;ui-dialog-titlebar-icon ui-dialog-titlebar-close ui-corner-all ui-state-hover ui-state-focus&quot;]/span[@class=&quot;ui-icon ui-icon-closethick&quot;]</value>
      <webElementGuid>8e895d78-127e-450c-96e7-64a59192c182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserRolesEditDlg']/div/a/span</value>
      <webElementGuid>690f081d-33a3-4552-9d8b-1e0a6d2dc24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/a/span</value>
      <webElementGuid>f5dd6673-91de-4906-88de-039d84178644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
