<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Approved</name>
   <tag></tag>
   <elementGuidId>ebd00a4a-a1eb-45d6-8bc0-76785f8fb1a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='AccumedHaadActivityListForm:datalist:j_idt486_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f45ea12b-3ff0-4219-a957-9451dbaed18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>57688bf9-0a56-4cdf-86ea-cfd1ecfc9fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Approved</value>
      <webElementGuid>5b853849-f6f7-422e-b65a-589cfb75fee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1ae77508-dcc6-4552-a734-01670aeaf425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fd9f391a-5aa5-4759-94cc-9204fa26dff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:datalist:j_idt486_1</value>
      <webElementGuid>83326191-c720-40c3-b393-43c6a3331b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approved</value>
      <webElementGuid>ec223797-8ae3-4c9a-8805-e455123cd924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:datalist:j_idt486_1&quot;)</value>
      <webElementGuid>bb38183a-d5ae-4bbd-8be3-e7258c76a560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='AccumedHaadActivityListForm:datalist:j_idt486_1']</value>
      <webElementGuid>a02f4f48-465f-4e45-9eb3-703f38b1636c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AccumedHaadActivityListForm:datalist:j_idt486_items']/li[2]</value>
      <webElementGuid>a471400a-b9cf-4b81-8821-862554e60f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Required'])[10]/following::li[1]</value>
      <webElementGuid>ecf35f39-fb1b-4624-8545-01a1f386789a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[2]</value>
      <webElementGuid>6d17b85b-d53c-4425-930b-ca8d710e75b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting Authorization'])[6]/preceding::li[1]</value>
      <webElementGuid>ab9a317b-8a83-47e5-b17d-854931306227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Covered'])[6]/preceding::li[2]</value>
      <webElementGuid>d0bd3a8f-9649-43b8-90e0-0a839b0b9b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/ul/li[2]</value>
      <webElementGuid>cef84a94-d0d5-4172-8a11-a5d110ef46d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'AccumedHaadActivityListForm:datalist:j_idt486_1' and (text() = 'Approved' or . = 'Approved')]</value>
      <webElementGuid>7935a567-cd16-4a54-b77f-640536e3fed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
