<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ui-button</name>
   <tag></tag>
   <elementGuidId>74eef41e-6ee6-46e7-9034-49a414791172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='phWLForm:phWLTbl:1:DetailsBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>722b86fe-7c62-4f16-bb86-215c8362e4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:phWLTbl:1:DetailsBtn</value>
      <webElementGuid>29115278-44a1-46d8-a959-5b701377ce4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phWLForm:phWLTbl:1:DetailsBtn</value>
      <webElementGuid>9e47ac89-b4bd-46c7-b7a3-3174bec11ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-state-focus ui-state-hover</value>
      <webElementGuid>c5ebc938-0485-4af5-b0f1-db477cf9e315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.bcn(this,event,[function(event){this.disabled = true;this.className += ' ui-state-disabled ';},function(event){PrimeFaces.ab({s:&quot;phWLForm:phWLTbl:1:DetailsBtn&quot;,p:&quot;phWLForm:phWLTbl&quot;,u:&quot;AccumedHaadActivityListForm AccumedHaadDiagnosisListForm pbmClaimDtlDlg phWLForm:phWLTbl:1:DetailsBtn&quot;,onst:function(cfg){startAjaxLoader('OPENING VISIT IN PROGRESS');;},onco:function(xhr,status,args){endAjaxLoader(); PF('pbmClaimDtlDlgWid').show() ;PF('dataTableActivity').filter();lockObject(1003369,'BMSClaimView');;}});return false;}]);</value>
      <webElementGuid>87c34703-f174-4514-8155-da4ee6b51808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>060d30bb-f781-411a-9ad6-f4e743ba34ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e0380e5-3475-401e-82ff-7ea1b5419c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7961d79a-ce43-48a0-9477-376a8855789d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ui-button</value>
      <webElementGuid>0cf6fe39-735d-4227-b114-1e0a67b57e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:1:DetailsBtn&quot;)</value>
      <webElementGuid>e524da3c-697f-4848-a0a2-168d13e76bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='phWLForm:phWLTbl:1:DetailsBtn']</value>
      <webElementGuid>0908007a-77b1-42e2-9c10-34ec03b18d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='phWLForm:phWLTbl_data']/tr[2]/td[13]/button</value>
      <webElementGuid>b6b24f6f-945f-4f4c-b3b3-24389365c2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Billed'])[3]/following::button[1]</value>
      <webElementGuid>dd8d4afc-dd80-47da-9fd8-6360931e2f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::button[1]</value>
      <webElementGuid>5ecd2f3d-d0f7-4cdd-b129-5ddb91d4fbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::button[1]</value>
      <webElementGuid>fd72ec53-0791-4e4e-9bc8-d3173d647e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[13]/button</value>
      <webElementGuid>e5cada46-0ba3-4ebe-8720-f02e3aa0fd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'phWLForm:phWLTbl:1:DetailsBtn' and @name = 'phWLForm:phWLTbl:1:DetailsBtn' and @type = 'submit' and (text() = 'ui-button' or . = 'ui-button')]</value>
      <webElementGuid>3fc56dbb-1d91-48a1-b3f4-4f0c49e27e4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
