<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ui-button</name>
   <tag></tag>
   <elementGuidId>47c553ad-ae7f-4d73-8b45-c4a3499e3aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='phWLForm:phWLTbl:1:DetailsBtn']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1ea59d3-b597-4651-8a8d-447e7e0ff734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>265510e3-169b-4d57-8efd-0bd2460c7fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ui-button</value>
      <webElementGuid>afdb8667-c8c6-4c8f-bc4f-2b5d493074ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:1:DetailsBtn&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>05bae894-307d-4b1f-b4aa-d39277cd2a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='phWLForm:phWLTbl:1:DetailsBtn']/span[2]</value>
      <webElementGuid>6327a071-ed27-4ddd-a214-40dcf584d51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Billed'])[3]/following::span[2]</value>
      <webElementGuid>8d08ee31-7512-4777-80e6-ff4d96c637a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::span[3]</value>
      <webElementGuid>c50be25c-5f1b-4897-b338-6031bbac7537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::span[2]</value>
      <webElementGuid>c2259755-4333-4d97-af8b-8188ff3fd28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[3]/preceding::span[4]</value>
      <webElementGuid>6a598d06-a918-4530-8da3-8d538e01e67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[13]/button/span[2]</value>
      <webElementGuid>491a7580-d553-4617-8d13-889d46a027df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ui-button' or . = 'ui-button')]</value>
      <webElementGuid>106976ca-f764-4235-8f8c-12d965eab0ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
