<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Activate</name>
   <tag></tag>
   <elementGuidId>11a71843-fc41-451e-b180-89179202dcb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='idAttachmentsDlgForm:attachments:0:j_idt2067']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dab72d66-f428-42b1-9b76-c110f66332d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>5503c022-8e1e-4fe4-8ba7-032b32aa04f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activate</value>
      <webElementGuid>b3d29cbf-b653-4af0-905d-afef03925a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idAttachmentsDlgForm:attachments:0:j_idt2067&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>a5c4ef7e-3934-464a-9f88-b6b018696350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='idAttachmentsDlgForm:attachments:0:j_idt2067']/span</value>
      <webElementGuid>07ab79f5-99a1-4236-8af4-786e64092d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/following::span[1]</value>
      <webElementGuid>4d6aa53b-a6bf-4fc6-9303-e5ad51530a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::span[2]</value>
      <webElementGuid>a24d4d31-f6aa-4859-b433-6d6a6b387aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotate Left'])[1]/preceding::span[4]</value>
      <webElementGuid>fc5dbbda-eac2-429e-9f90-5d85789afdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotate Right'])[1]/preceding::span[6]</value>
      <webElementGuid>95a7f28d-2271-41b9-aab1-674ac61ab665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activate']/parent::*</value>
      <webElementGuid>0012cfa8-8539-47fa-9f5c-9eaf78683627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button/span</value>
      <webElementGuid>79a7d27a-acf4-4408-ba76-a180ec0ad2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Activate' or . = 'Activate')]</value>
      <webElementGuid>085a76a0-dc08-422c-a954-6301561d85e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
