<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Payment List</name>
   <tag></tag>
   <elementGuidId>a6a94062-9fc9-485d-8a52-f91c9b187432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.verticalPaymentColumn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='paymentForm']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0fc8e13c-391f-4df4-95fb-bd54f498f296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verticalPaymentColumn</value>
      <webElementGuid>fa06533d-7968-4012-b5e8-07a12a658bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment List</value>
      <webElementGuid>a21a903a-1ecd-4d08-9e25-807b74ff9e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentForm&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;verticalPaymentColumn&quot;]</value>
      <webElementGuid>1283d22a-84b2-4b97-9bac-832c7ca50081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/table/tbody/tr/td</value>
      <webElementGuid>79044222-9d3d-473e-8225-842f79e4d3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[5]/following::td[1]</value>
      <webElementGuid>fbb4f862-587b-44bb-83fe-88a6f2fdafa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records found.'])[2]/following::td[1]</value>
      <webElementGuid>a70dde4f-ce72-4636-a05a-e0a1bf77367b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Amount :'])[1]/preceding::td[5]</value>
      <webElementGuid>45d69ddc-d5d9-4b59-be37-51bcdd03a3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[4]/table/tbody/tr/td</value>
      <webElementGuid>abb7b02f-a094-4872-9a05-b4cd8eea605c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Payment List' or . = 'Payment List')]</value>
      <webElementGuid>f0c75afb-a537-4335-805f-963b138fc741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
