<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AccumedPatientInsuranceCreateFormpat_cc52de</name>
   <tag></tag>
   <elementGuidId>6ab000df-d8f1-4c16-84a6-672ecb8e68e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientInsuranceCreateForm:patientInsuranceId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f7bbdab-4415-4213-8fd2-5ba72b251e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:patientInsuranceId</value>
      <webElementGuid>e01cb094-5486-45d2-a767-52f167e4a68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:patientInsuranceId</value>
      <webElementGuid>ad7b62fd-5af6-4992-ac4f-ffe6d9f2d557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2842d966-0aef-4b33-bad3-d487580530a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>- The patient's insurance member number, if the patient is claiming insurance.                                              - Otherwise, this field should be left empty.</value>
      <webElementGuid>b22a045e-3de1-4efd-9991-e3c3cebb5bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>e9dac892-8fb0-46dd-aba8-88ef28a43515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7b261b27-aa10-405b-be59-58a7e2db21f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53445c7f-404e-4f66-b188-f4d092cfde95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7dbab40-3a23-4cf0-aeb0-2c8b9bc7133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:patientInsuranceId&quot;)</value>
      <webElementGuid>32d12b1e-6bce-42af-a730-8d0aa24a249f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientInsuranceCreateForm:patientInsuranceId']</value>
      <webElementGuid>843efbbf-9e03-41a4-b702-3fdb369609b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientInsuranceCreateForm:j_idt1254']/tbody/tr/td[2]/input</value>
      <webElementGuid>7840e324-808d-46d3-a7ec-54854cc2e964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>082a49db-daea-4424-b942-e568b5ba16fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientInsuranceCreateForm:patientInsuranceId' and @name = 'AccumedPatientInsuranceCreateForm:patientInsuranceId' and @type = 'text' and @title = concat(&quot;- The patient&quot; , &quot;'&quot; , &quot;s insurance member number, if the patient is claiming insurance.                                              - Otherwise, this field should be left empty.&quot;)]</value>
      <webElementGuid>51157bba-9592-435c-a428-258507801a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
