<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Dialysis</name>
   <tag></tag>
   <elementGuidId>88395705-1d2a-437e-85da-6bde0d0c9638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='InvoiceForm:department_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca0bc5b5-9af5-4343-b96a-bca4341f8b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>8c82d3ea-2b61-4735-93ed-4eb0e588e695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Dialysis</value>
      <webElementGuid>68685fad-8ee7-4d60-a1ca-dd54f82f8733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4e3ac15c-8fc3-4699-83d9-6ae3b1603281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a069006d-7315-48a1-9e6e-3151a1a57d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:department_8</value>
      <webElementGuid>f945f402-2d74-4bf7-8e88-b0811744318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dialysis</value>
      <webElementGuid>7c1e1e20-753f-43c2-85d8-0a0e100d2600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:department_8&quot;)</value>
      <webElementGuid>0c5a6c8b-8722-44e1-8ff0-244090695aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='InvoiceForm:department_8']</value>
      <webElementGuid>f75f34ba-f303-4c69-be3d-173f5a8bc089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='InvoiceForm:department_items']/li[9]</value>
      <webElementGuid>82815111-efc0-4ea9-976c-cf9d47efc422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DermaVen'])[4]/following::li[1]</value>
      <webElementGuid>922e0793-3289-49f0-815e-69a9d280c051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dental'])[14]/following::li[2]</value>
      <webElementGuid>ab688deb-6790-4c44-aae1-35296f98042f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENT'])[12]/preceding::li[1]</value>
      <webElementGuid>553106d3-35a5-4ccb-a695-02c4eb2cd5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency'])[4]/preceding::li[2]</value>
      <webElementGuid>b97137ea-7085-45f8-a73a-f96a5ae5301d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[84]/div/ul/li[9]</value>
      <webElementGuid>79f0cf3d-33b0-439b-8112-26532fc56350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'InvoiceForm:department_8' and (text() = 'Dialysis' or . = 'Dialysis')]</value>
      <webElementGuid>0f30e8b6-9f3b-4e50-a287-d5e931ee470a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
