<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Patient not availed service</name>
   <tag></tag>
   <elementGuidId>6a2128a7-23fb-42da-816c-f59f179f5ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='billItemsForm:refundReason_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e7f0f7ee-f011-4c1f-9c85-7fb8d8d02a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>2b425d13-72e9-4135-a25c-d1915767edf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Patient not availed service</value>
      <webElementGuid>d3c3206d-5996-4132-af32-13693e0d075c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>df408ed3-b3bd-4dd1-9fba-7a4fbf177703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8fa488b7-4237-4fb4-bc73-69275313ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billItemsForm:refundReason_3</value>
      <webElementGuid>e1327875-4de1-499d-a9a9-a4f7ed8598b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient not availed service</value>
      <webElementGuid>438ad52e-ab67-46de-8a52-cd6c01082efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billItemsForm:refundReason_3&quot;)</value>
      <webElementGuid>dd7fe1a2-024b-4d5d-b2e2-c2d5335f57c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='billItemsForm:refundReason_3']</value>
      <webElementGuid>63c1d09b-6c9e-42d8-97a3-160a98752615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='billItemsForm:refundReason_items']/li[4]</value>
      <webElementGuid>804b7ab0-655d-4049-a9b0-690ffe959e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[2]/following::li[1]</value>
      <webElementGuid>fefefd02-e10e-4a74-aa26-65712a609542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance approved the service'])[2]/following::li[2]</value>
      <webElementGuid>bc916c2c-638f-488b-a7d3-8737668e4dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service not available'])[2]/preceding::li[1]</value>
      <webElementGuid>898b53b5-262f-4344-bfcd-3d9b16a601e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/ul/li[4]</value>
      <webElementGuid>879b1c15-efd2-4843-ae08-4026f370bd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'billItemsForm:refundReason_3' and (text() = 'Patient not availed service' or . = 'Patient not availed service')]</value>
      <webElementGuid>206a7358-c95d-4ac4-9430-89bc87a345b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
