<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Preview</name>
   <tag></tag>
   <elementGuidId>c5cfacc0-f89b-43e4-8c9e-fc7d5e87ed52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refundForm:dtBills:2:viewInvoice']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e283bf33-51e2-4a4b-a517-e966e25ee41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>24b7d65f-8a0a-4e3a-ac10-a19cf0df4316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>40f22a57-ca70-4042-b2a7-da5d84a3552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refundForm:dtBills:2:viewInvoice&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>67098810-80b5-4b1f-b95d-398d24225383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='refundForm:dtBills:2:viewInvoice']/span[2]</value>
      <webElementGuid>fc37f9d1-254d-4222-9a26-38a52b480d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund'])[3]/following::span[2]</value>
      <webElementGuid>94b14097-4a22-4f4a-b787-54244e1591cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[3]/following::span[4]</value>
      <webElementGuid>2c41ef7e-a8ba-4901-9213-ebcf49aefccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APM-IP-0000886'])[1]/preceding::span[2]</value>
      <webElementGuid>6853932e-01d1-4707-ab20-b144cd4482a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mrm--088'])[1]/preceding::span[3]</value>
      <webElementGuid>ae170723-d064-4995-9418-e31675216f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[11]/button/span[2]</value>
      <webElementGuid>3d44b995-bd6e-450b-86e9-3ea991ecc447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Preview' or . = 'Preview')]</value>
      <webElementGuid>06acbf78-0d23-4f5d-b3a7-533f060ecf01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
