<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ConfirmationAre you sureYesNo</name>
   <tag></tag>
   <elementGuidId>b30d31ce-b34f-48cd-9058-60aef4c834d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='SystemConfigurationForm:confirmDialog'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9801509d-7a2a-4cf1-a47d-b3ea13f4c4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SystemConfigurationForm:confirmDialog</value>
      <webElementGuid>f8a6f643-dae6-4cae-b7c5-b1404192fb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-confirm-dialog ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container</value>
      <webElementGuid>b28b0442-1276-48eb-8edd-c4482fa09c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>2ebe4156-4c0d-437e-8be6-54cb999aceb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>SystemConfigurationForm:confirmDialog_title</value>
      <webElementGuid>c091bd9c-5db8-49f6-8678-009c5d518ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec4bbbb3-ce98-4982-8148-9ffff1331a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>cabf5c11-7dd4-4dd4-ad08-2b038dc3f4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ConfirmationAre you sure?YesNo</value>
      <webElementGuid>504bbaeb-56b5-4a61-aeeb-20d079ea246b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ui-layout-container&quot;]/div[@id=&quot;SystemConfigurationForm:confirmDialog&quot;]</value>
      <webElementGuid>bcb55b30-0ef0-467c-a963-438dc3bdf7a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='SystemConfigurationForm:confirmDialog'])[2]</value>
      <webElementGuid>32b6d0c8-cbf1-4a2e-90de-04bc3fecb67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[1]</value>
      <webElementGuid>403b00a4-79f4-4b6e-b58d-08a3e84ff5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[4]/following::div[1]</value>
      <webElementGuid>4f5106e7-35ab-444e-8530-2b29b9a461db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]</value>
      <webElementGuid>4ccbb6ba-ec5e-4baa-befc-2a20d331e2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SystemConfigurationForm:confirmDialog' and (text() = 'ConfirmationAre you sure?YesNo' or . = 'ConfirmationAre you sure?YesNo')]</value>
      <webElementGuid>34dc2ddd-693b-44c7-8dae-08070aceb2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
