<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Updating Department SuccessUpdating Department Success</name>
   <tag></tag>
   <elementGuidId>019e95d6-7e1e-46e7-844a-8bfbe610e502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LookupMappingForm:LookupMappingMessages_container']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-growl-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ce489af-62f0-4590-822c-6811fc22c920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-growl-item</value>
      <webElementGuid>f2b5ed62-1029-4d36-8da9-f878733af53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Updating Department SuccessUpdating Department Success</value>
      <webElementGuid>7e6220b8-180a-43dd-8833-1342d7cfbf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LookupMappingForm:LookupMappingMessages_container&quot;)/div[@class=&quot;ui-growl-item-container ui-state-highlight ui-corner-all ui-helper-hidden ui-shadow ui-growl-info&quot;]/div[@class=&quot;ui-growl-item&quot;]</value>
      <webElementGuid>50f22729-166f-483e-9371-381acf6eaf7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LookupMappingForm:LookupMappingMessages_container']/div/div</value>
      <webElementGuid>fee6a051-4bf1-427a-9797-0c73d8f81a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[3]/following::div[3]</value>
      <webElementGuid>d29b306a-618f-404d-932d-46f7994383b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{$STATUS}:Response Status'])[1]/following::div[3]</value>
      <webElementGuid>30365fce-c6c9-40f5-ba98-b272dc1ee954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/preceding::div[4]</value>
      <webElementGuid>cdf0a0b5-bfbe-4125-9f8c-cdaf0dfcb8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div</value>
      <webElementGuid>1f6fe767-c119-4085-b3c5-7db7bc7d55f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Updating Department SuccessUpdating Department Success' or . = 'Updating Department SuccessUpdating Department Success')]</value>
      <webElementGuid>c2837769-d946-4083-884b-2f832c5eee84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
