<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ALL_1 (1)</name>
   <tag></tag>
   <elementGuidId>2270bcd2-bf52-4546-80b6-bf3bb328026e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='MISReportsForm:j_idt225_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>571e1d87-83cd-4530-9d5b-97066022278b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectcheckboxmenu-label ui-corner-all ui-state-hover</value>
      <webElementGuid>eba7ff83-c8e7-41dd-9797-1cc6da310f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt225_label</value>
      <webElementGuid>a9c8de2b-26f4-4134-972a-6d39af1a1e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL</value>
      <webElementGuid>585c1b79-60f3-461e-8d78-9bbb3d509ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt225_label&quot;)</value>
      <webElementGuid>e08558db-a049-4ccd-997b-0119bb001ec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='MISReportsForm:j_idt225_label']</value>
      <webElementGuid>da0288e5-c886-4d52-8ec9-925eb33d481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MISReportsForm:j_idt225']/span/label</value>
      <webElementGuid>666e1bef-0a8c-4148-ac6b-c5506e31cd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testtype'])[1]/following::label[1]</value>
      <webElementGuid>77c5bbb8-ccfd-4a28-a963-6f83ee9914d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='plaster room'])[1]/following::label[2]</value>
      <webElementGuid>38b009fd-87da-4ab0-b32b-89f56ce5171e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Report'])[1]/preceding::label[1]</value>
      <webElementGuid>c0f8a1af-6b7f-4eb6-a738-ab5142266a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/preceding::label[1]</value>
      <webElementGuid>b1cec805-c739-4d1b-86bd-a51a1e77d80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/span/label</value>
      <webElementGuid>fca2404b-b242-4fca-a56d-1c2d071b3550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'MISReportsForm:j_idt225_label' and (text() = 'ALL' or . = 'ALL')]</value>
      <webElementGuid>eafc3f79-5490-4e6a-9b77-dbf5f1b1662e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
