<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_708530NEXIUM 20MG TAB  PACK QTY28 ASTRAZENECA</name>
   <tag></tag>
   <elementGuidId>54a7d1e0-a46a-4df0-9593-479a6e52e445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='MISReportsForm:autoActivityCode_panel']/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ui-autocomplete-item.ui-autocomplete-list-item.ui-corner-all.ui-state-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>549b1875-74c6-4dc5-bfb3-04c17b529789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-item ui-autocomplete-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>960eccc4-a4b0-4470-94c4-748260896a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-value</name>
      <type>Main</type>
      <value>708530</value>
      <webElementGuid>29ba0ee5-4026-4fd2-843f-0696385fab15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-label</name>
      <type>Main</type>
      <value>708530|NEXIUM 20MG TAB  PACK QTY:28 ASTRAZENECA</value>
      <webElementGuid>e1aaacfa-d35e-4b81-8e28-ca1506e543f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>42347ca5-4243-499c-ae9d-339a2ac2623c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>708530|NEXIUM 20MG TAB  PACK QTY:28 ASTRAZENECA</value>
      <webElementGuid>1a5f7809-56fc-4d39-a909-19c2d132c414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:autoActivityCode_panel&quot;)/ul[@class=&quot;ui-autocomplete-items ui-autocomplete-list ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/li[@class=&quot;ui-autocomplete-item ui-autocomplete-list-item ui-corner-all ui-state-highlight&quot;]</value>
      <webElementGuid>c912dfb4-2277-400b-a555-511c2a03ebca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='MISReportsForm:autoActivityCode_panel']/ul/li</value>
      <webElementGuid>1dd08d48-26ca-4e42-87a4-ee7a3bed8de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testtype'])[2]/following::li[1]</value>
      <webElementGuid>ab592ee1-5dc1-4384-8663-9a4c838114f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='plaster room'])[2]/following::li[2]</value>
      <webElementGuid>01a396bd-a7db-4288-a4ed-80c509c3b48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='70']/parent::*</value>
      <webElementGuid>ecc4a828-1553-4437-b7bb-7d92e68d46b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>36223e1f-0277-4fcf-ad70-5a4b6ec74ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '708530|NEXIUM 20MG TAB  PACK QTY:28 ASTRAZENECA' or . = '708530|NEXIUM 20MG TAB  PACK QTY:28 ASTRAZENECA')]</value>
      <webElementGuid>ec0ee42f-15b1-40d4-bd43-899859ce5137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
