<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Department wise Patient count for Servic_e3f6c2</name>
   <tag></tag>
   <elementGuidId>8415607f-2475-4a4b-91cb-dc8408144e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='MISReportsForm:j_idt185_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>52dd8a51-f750-4d41-a775-c71ce2073bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>884d835a-fab1-4537-aee2-1a1eb757ca76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Department wise Patient count for Service availed</value>
      <webElementGuid>0ba0811e-88c5-43cf-99a6-3eb2f212e56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>57b04170-9454-4ca2-b9b0-6e9579686d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5747c1e0-569b-4f2a-9f70-5e44353f3d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt185_1</value>
      <webElementGuid>c1f69684-420e-4342-a842-e323bd83a131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Department wise Patient count for Service availed</value>
      <webElementGuid>f3f8dde4-3255-4778-8ed2-963ffa747b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt185_1&quot;)</value>
      <webElementGuid>9efbe7bd-6d1b-4aa1-aeeb-2977169d5682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='MISReportsForm:j_idt185_1']</value>
      <webElementGuid>b09538ce-ef63-4529-99e8-cb2b87717517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='MISReportsForm:j_idt185_items']/li[2]</value>
      <webElementGuid>8e7219ba-6e5b-453d-9582-48eeaebaeada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Revenue'])[3]/following::li[1]</value>
      <webElementGuid>aed2dc30-4f85-4b78-8996-480b02bb86b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/following::li[2]</value>
      <webElementGuid>44bad985-49e3-4427-b7d5-b3a77887c8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department Wise Revenue Report'])[2]/preceding::li[1]</value>
      <webElementGuid>3359032d-8bc6-4e10-8b08-c390fe8a52a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor wise Patient count and Revenue'])[2]/preceding::li[2]</value>
      <webElementGuid>0ebb4cf9-7800-4fc7-aa34-2761be982e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/ul/li[2]</value>
      <webElementGuid>499337ad-5a47-4e9d-80e1-21d354af7e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'MISReportsForm:j_idt185_1' and (text() = 'Department wise Patient count for Service availed' or . = 'Department wise Patient count for Service availed')]</value>
      <webElementGuid>f4ee5663-e297-4227-8b36-e245d59bba34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
