<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Monthly Revenue</name>
   <tag></tag>
   <elementGuidId>abcf83bc-4510-4684-af01-ef8ddd464de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='MISReportsForm:j_idt185_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8bc47297-f91e-450c-bf89-cc46875f8e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>2722dd9a-1628-41e6-a084-97343e2868a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Monthly Revenue</value>
      <webElementGuid>481ae896-2482-4e7e-9e47-3fb6cf1575ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4b54934c-3510-4a3d-80de-bf1aabbedac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1f418a30-004e-426e-910c-2b2d107932e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt185_0</value>
      <webElementGuid>d38b40ce-532b-4106-8047-f33b214c18fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly Revenue</value>
      <webElementGuid>efd42707-6f8c-4735-ae11-92d1e4717dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt185_0&quot;)</value>
      <webElementGuid>071b3973-783c-4e86-a719-ce128a8285f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='MISReportsForm:j_idt185_0']</value>
      <webElementGuid>6c2d7d10-ba43-4d04-9daf-9c92531ad798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='MISReportsForm:j_idt185_items']/li</value>
      <webElementGuid>6d9fd1ff-96db-4314-b376-bb0c267872ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/following::li[1]</value>
      <webElementGuid>634d4458-4415-4a9d-9c39-d26c6691c39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Report'])[1]/following::li[1]</value>
      <webElementGuid>845fcab8-4955-49b8-a1dc-87338846eb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department wise Patient count for Service availed'])[2]/preceding::li[1]</value>
      <webElementGuid>f855562a-a732-4087-97c6-842638fc4f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department Wise Revenue Report'])[2]/preceding::li[2]</value>
      <webElementGuid>7d617c13-75ad-4b3a-995f-3c62343b9275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/ul/li</value>
      <webElementGuid>0e06a8b6-ec37-4d6b-9ad7-3d430e94500b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'MISReportsForm:j_idt185_0' and (text() = 'Monthly Revenue' or . = 'Monthly Revenue')]</value>
      <webElementGuid>460e150e-0974-4ff5-8c8c-05172063d9d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
