<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_y_ui-chkbox-icon ui-icon ui-icon-blank</name>
   <tag></tag>
   <elementGuidId>2d034ab0-040c-4237-b526-b27f7652ee80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MISReportsForm:j_idt225_panel']/div/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-chkbox-icon.ui-icon.ui-icon-blank</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d16f4a4f-e488-4fcc-a757-59e5c2bbda6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-icon ui-icon ui-icon-blank</value>
      <webElementGuid>605d35a4-46d1-419e-90c8-765704fb3957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt225_panel&quot;)/div[@class=&quot;ui-widget-header ui-corner-all ui-selectcheckboxmenu-header ui-helper-clearfix&quot;]/div[@class=&quot;ui-chkbox ui-widget&quot;]/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]/span[@class=&quot;ui-chkbox-icon ui-icon ui-icon-blank&quot;]</value>
      <webElementGuid>fb8a398e-6351-48db-87ad-58ecd2136782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MISReportsForm:j_idt225_panel']/div/div/div[2]/span</value>
      <webElementGuid>cf061b43-a33d-45ea-8aa0-b00a8185c098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div[2]/span</value>
      <webElementGuid>31feb1cc-b9fd-4ed4-9b66-e349b22aa222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
