<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_AllOPIPER</name>
   <tag></tag>
   <elementGuidId>b8598d7f-ec8f-495e-b11b-b391f3ee4cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='MISReportsForm:j_idt254_items']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1edeb536-4e06-4ab5-813b-143b10ed61c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt254_items</value>
      <webElementGuid>ebe078a0-d8c3-445f-9cff-5e232e6b84b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset</value>
      <webElementGuid>0e9ea4f3-1d3e-4190-ad1b-65d832c55c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>856fe3bb-6b4a-40f1-b318-402ad97f253d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>MISReportsForm:j_idt254_0</value>
      <webElementGuid>05418c1b-e021-4f51-b797-fdcd93935ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllOPIPER</value>
      <webElementGuid>71b1159b-e25f-4717-b6e2-47cd0dabd2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MISReportsForm:j_idt254_items&quot;)</value>
      <webElementGuid>7425db08-abf5-48c8-ba5f-6a40c35a99c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='MISReportsForm:j_idt254_items']</value>
      <webElementGuid>0bc5040f-67d2-4f47-8392-2bacd29adf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MISReportsForm:j_idt254_panel']/div/ul</value>
      <webElementGuid>f10db6e4-49e7-4438-8da3-2a90d1b2f938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'MISReportsForm:j_idt254_items', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>d478ca55-1ef4-4df9-bdba-2150be3cacac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREDIT'])[1]/following::ul[1]</value>
      <webElementGuid>e0b7b328-8f90-428b-baec-4d8257e79211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/ul</value>
      <webElementGuid>de345933-3740-473f-b9a0-da995dfef25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'MISReportsForm:j_idt254_items' and (text() = 'AllOPIPER' or . = 'AllOPIPER')]</value>
      <webElementGuid>85d42a2d-2137-489e-aae3-914004fd7773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
