<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tawuniya cooperative  Insurance Company</name>
   <tag></tag>
   <elementGuidId>44bdeaea-cfda-4dea-aecf-7e64cd46e68f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='phWLForm:payer_autoFilter_101']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a311fe5a-1fde-4cc9-99ba-5931b71885e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>75d94787-3d24-4b5e-9cee-b118af28ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Tawuniya cooperative  Insurance Company</value>
      <webElementGuid>a7d93417-3661-41d8-ad82-b109185eaa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dc08e673-5fc5-4113-bc94-6b5ddeb1f69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e921ec5e-002d-424e-93fa-0f52c326e25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:payer_autoFilter_101</value>
      <webElementGuid>04c76a5d-ec98-4cd0-89d6-d370323a3c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tawuniya cooperative  Insurance Company</value>
      <webElementGuid>022bb2e4-2d81-48e4-913f-6e4d8ea64f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:payer_autoFilter_101&quot;)</value>
      <webElementGuid>54951cff-b958-4d91-966d-2a30669603e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='phWLForm:payer_autoFilter_101']</value>
      <webElementGuid>69979e27-b9d2-416b-ad45-f6ce10fd9e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='phWLForm:payer_autoFilter_items']/li[102]</value>
      <webElementGuid>2ca93bd2-fc5a-4911-bff9-a04ccd6d818b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SY'])[2]/following::li[1]</value>
      <webElementGuid>f9a2d762-af28-4f91-a3bf-c146b7a6413f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SR'])[2]/following::li[2]</value>
      <webElementGuid>9c21a83f-fd44-4c89-9608-103e0b7b3907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TCS'])[2]/preceding::li[1]</value>
      <webElementGuid>d7abce08-b831-46a2-80a7-54ab9b0bde30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[2]/preceding::li[2]</value>
      <webElementGuid>01a2133b-99a1-4e17-8931-00b58de6204d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[102]</value>
      <webElementGuid>522eebe4-c7c1-4187-a395-d067c7825ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'phWLForm:payer_autoFilter_101' and (text() = 'Tawuniya cooperative  Insurance Company' or . = 'Tawuniya cooperative  Insurance Company')]</value>
      <webElementGuid>fc2a607e-edb8-4734-95f3-b36b41cd4d9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
