<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GGGG ffasdsd GGGG</name>
   <tag></tag>
   <elementGuidId>a2183ec5-7b61-4bb6-8b71-1f3623d3d3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='phWLForm:phWLTbl:1:j_idt218']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ed14f72-b543-48e8-a03c-25993135199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:phWLTbl:1:j_idt218</value>
      <webElementGuid>002a75d0-d6cd-42b4-8d04-95e154a87a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a61a08d3-c7db-4463-b074-9ae29da33c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget</value>
      <webElementGuid>4e1d8905-6aff-4c2b-a781-87ca2085a70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.disabled = true;this.className += ' ui-state-disabled ';;PrimeFaces.ab({s:&quot;phWLForm:phWLTbl:1:j_idt218&quot;,p:&quot;phWLForm:phWLTbl&quot;,u:&quot;AccumedHaadDiagnosisListForm pbmClaimDtlDlg phWLForm:phWLTbl:1:j_idt218 paymentForm actionsButtonsForm&quot;,onst:function(cfg){startAjaxLoader('OPENING VISIT IN PROGRESS');;},onco:function(xhr,status,args){endAjaxLoader(); PF('pbmClaimDtlDlgWid').show()  ;;}});return false;</value>
      <webElementGuid>f9d2bf1f-676a-4cb9-af48-00f3860e0ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GGGG ffasdsd GGGG</value>
      <webElementGuid>399eb370-5198-4f75-8217-e0eaab00fd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:1:j_idt218&quot;)</value>
      <webElementGuid>d5321c9b-0c3f-40b0-8e96-0c4e7c25ccb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='phWLForm:phWLTbl:1:j_idt218']</value>
      <webElementGuid>501e439b-ad14-436b-af42-19fa8be34925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='phWLForm:phWLTbl_data']/tr[2]/td/a</value>
      <webElementGuid>d6878adc-48da-4fb1-96b2-07435afb3fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'GGGG ffasdsd GGGG')]</value>
      <webElementGuid>5e9f75aa-0e1e-4d7c-909f-c83494c0e5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[1]/following::a[1]</value>
      <webElementGuid>eea9ce1a-18cf-4969-8d71-f5e87836c448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billed'])[2]/following::a[1]</value>
      <webElementGuid>c7ef864c-0083-46c6-a629-dfdd0d422783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mrm-099997'])[1]/preceding::a[1]</value>
      <webElementGuid>f1ce818c-f23e-440c-9e98-bc7a276a3b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APM-IP-0000885'])[1]/preceding::a[1]</value>
      <webElementGuid>35c9621d-bfe8-493a-93e1-7f129be3dff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GGGG ffasdsd GGGG']/parent::*</value>
      <webElementGuid>13cbb28f-7896-42f5-b0f9-d6d72eeb8b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[25]</value>
      <webElementGuid>2f5c0d98-f73c-41df-9899-7efe57a0cd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/a</value>
      <webElementGuid>1f38fba0-adee-4fd3-afea-1fc79c667645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'phWLForm:phWLTbl:1:j_idt218' and @href = '#' and (text() = 'GGGG ffasdsd GGGG' or . = 'GGGG ffasdsd GGGG')]</value>
      <webElementGuid>e0ef8fec-0ca0-49c3-8e91-b74d23c77f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
