<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KRANTHET hahahah JJJDHDHD</name>
   <tag></tag>
   <elementGuidId>da7cb8aa-ad73-45bd-9427-d97d998635ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='phWLForm:phWLTbl:0:j_idt218']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad0492ee-730e-45cb-be40-c9bd5a755121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phWLForm:phWLTbl:0:j_idt218</value>
      <webElementGuid>0bbb3120-7e9a-4bb2-937a-fee8279e21f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>299eb1a5-3cf0-4c34-8d99-d8d61f53b87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget</value>
      <webElementGuid>07442219-7e13-4415-a239-d6f6e3fd88a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.disabled = true;this.className += ' ui-state-disabled ';;PrimeFaces.ab({s:&quot;phWLForm:phWLTbl:0:j_idt218&quot;,p:&quot;phWLForm:phWLTbl&quot;,u:&quot;AccumedHaadDiagnosisListForm pbmClaimDtlDlg phWLForm:phWLTbl:0:j_idt218 paymentForm actionsButtonsForm&quot;,onst:function(cfg){startAjaxLoader('OPENING VISIT IN PROGRESS');;},onco:function(xhr,status,args){endAjaxLoader(); PF('pbmClaimDtlDlgWid').show()  ;;}});return false;</value>
      <webElementGuid>49b58064-a0b1-4251-9e3f-989760da8703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KRANTHET hahahah JJJDHDHD</value>
      <webElementGuid>1c314081-c91c-437b-9a04-b60e74f20005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:0:j_idt218&quot;)</value>
      <webElementGuid>2b8dd14b-88c7-41f1-a443-c4cffbcaa025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='phWLForm:phWLTbl:0:j_idt218']</value>
      <webElementGuid>d55872b1-df6b-4c30-9f73-c1e5879cd7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='phWLForm:phWLTbl_data']/tr/td/a</value>
      <webElementGuid>02410b08-99a1-459d-b59b-69332c3b5592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KRANTHET hahahah JJJDHDHD')]</value>
      <webElementGuid>a539e744-4d2a-498e-84f6-ac57b50270a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::a[1]</value>
      <webElementGuid>ba2e60e9-4d12-49b6-936a-0093a22c3756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt No'])[1]/following::a[1]</value>
      <webElementGuid>25522d9d-8375-4d41-904d-c1ed70825fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mrn-09/*8'])[1]/preceding::a[1]</value>
      <webElementGuid>801449f2-4875-4d11-a8d8-f5472536b2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APM-IP-0000884'])[1]/preceding::a[1]</value>
      <webElementGuid>ecad6ee2-80fb-4e85-946e-d81432aaafab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KRANTHET hahahah JJJDHDHD']/parent::*</value>
      <webElementGuid>3ef39cac-d36d-48f4-b8de-1fd2b20f0334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[24]</value>
      <webElementGuid>3384c32d-5175-4f4a-91e1-370d07f8fd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>4186fd2c-7d19-43a3-92dc-2e32196359a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'phWLForm:phWLTbl:0:j_idt218' and @href = '#' and (text() = 'KRANTHET hahahah JJJDHDHD' or . = 'KRANTHET hahahah JJJDHDHD')]</value>
      <webElementGuid>e94f62ce-d948-42f0-890e-aacb50d5591b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
