<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merge Bill_mergeBillDtlFormitem_input</name>
   <tag></tag>
   <elementGuidId>a7c36227-0279-44ec-84f1-f64a41d2816e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mergeBillDtlForm:item_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4a33d20-7b62-40fb-bf2e-f18ee32a19d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mergeBillDtlForm:item_input</value>
      <webElementGuid>81d48d1f-c9fb-4266-b998-0d4bd546d979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mergeBillDtlForm:item_input</value>
      <webElementGuid>9b3e09e2-13ba-457d-9002-9ccd0f991387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8297f615-0606-425d-8d22-23106606a9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>d6870b95-9a7c-4cfa-9da5-5d714893d8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a00b6a26-049d-4ebe-9f0d-b362b31d4f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by National ID, Name and Phone Number</value>
      <webElementGuid>ad0d0a94-bfc4-44ad-88f1-5ed384cd18b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c22ac9df-11a0-4073-b86e-a529a4e216bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search by National ID, Name and Phone Number.</value>
      <webElementGuid>909fccc0-cca0-4fe9-a1fd-e540ba5d472e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ef24d8a3-8c91-4d88-9c43-08fcb3f8a0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c18d4670-6458-496a-9dc3-0e11269ee4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e86fb08a-2162-444d-8c4f-40f65cf768ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>578dcfc8-ce39-49f5-9b72-d0feab071324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mergeBillDtlForm:item_input&quot;)</value>
      <webElementGuid>679adf7f-3b21-4c1f-83b8-44a19eb8e904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mergeBillDtlForm:item_input']</value>
      <webElementGuid>87b36132-0e6b-47a7-bfba-3501a809c9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mergeBillDtlForm:item']/input</value>
      <webElementGuid>734ad38c-abaf-4d6d-9ec3-6b70f46350b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>13334745-62ec-4865-b1dc-1809f2d27e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mergeBillDtlForm:item_input' and @name = 'mergeBillDtlForm:item_input' and @type = 'text' and @placeholder = 'Search by National ID, Name and Phone Number' and @title = 'Search by National ID, Name and Phone Number.']</value>
      <webElementGuid>ec23d056-2c28-4449-9bdf-44a16cb53771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
