<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rows Per Page_ui-button-icon-left ui-icon ui-c ui-icon-dispense</name>
   <tag></tag>
   <elementGuidId>69effe32-3e12-4900-9a64-bd091bf8bb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mergeBillDtlForm:mergeInvoice']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5eb14ef6-a82c-4e6a-afa6-394fe790d713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c ui-icon-dispense</value>
      <webElementGuid>dfcb6c73-72db-47e1-a7da-ac7f0875d40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mergeBillDtlForm:mergeInvoice&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c ui-icon-dispense&quot;]</value>
      <webElementGuid>69c3cd03-f8aa-4f78-9526-1cfd76dee7b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='mergeBillDtlForm:mergeInvoice']/span</value>
      <webElementGuid>77cf9850-b42f-457f-9f86-0438984fb1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/div[2]/form/table/tbody/tr/td/button/span</value>
      <webElementGuid>0cee42f6-f1bd-45d4-b790-6400fe98827f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
