<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Patient not availed service</name>
   <tag></tag>
   <elementGuidId>09622607-2df6-40ee-9d8a-bbc71d50ea4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='RefundAdvanceCollectionDlgForm:refundReason_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>53449494-2b0d-45ea-9457-f461c009d915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>4d0bd789-08b6-4504-b4fd-cba0ee15c238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Patient not availed service</value>
      <webElementGuid>b5a91310-cd58-4e7a-9d76-75ce9492335c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e7cbf725-193a-4d4f-a46e-af4372811306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>684bf9f3-7f50-4127-85e3-ba50c75223c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RefundAdvanceCollectionDlgForm:refundReason_3</value>
      <webElementGuid>1885e8e2-8d71-4698-be51-fb3c3971e203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient not availed service</value>
      <webElementGuid>551056fd-a965-4b68-aab0-4b483e226758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RefundAdvanceCollectionDlgForm:refundReason_3&quot;)</value>
      <webElementGuid>55976111-a16c-49a7-bd6e-fda6ccfdda55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='RefundAdvanceCollectionDlgForm:refundReason_3']</value>
      <webElementGuid>65240b57-c478-4251-adb9-55f6d52eb83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='RefundAdvanceCollectionDlgForm:refundReason_items']/li[4]</value>
      <webElementGuid>a6e2f63a-17ab-4b4c-b05b-c4a5c281a7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[2]/following::li[1]</value>
      <webElementGuid>f2785c23-7b0c-4e49-a206-1b2e89c96698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance approved the service'])[2]/following::li[2]</value>
      <webElementGuid>599a6283-90fa-4a09-8a1e-5ba7963ab690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service not available'])[2]/preceding::li[1]</value>
      <webElementGuid>84057e7f-7758-48dc-8d89-9baafa50dcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/ul/li[4]</value>
      <webElementGuid>e112fad4-7f54-4264-acf1-1c72658bfdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'RefundAdvanceCollectionDlgForm:refundReason_3' and (text() = 'Patient not availed service' or . = 'Patient not availed service')]</value>
      <webElementGuid>0e8a9f37-81c2-4f57-b944-860989ef85a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
