<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes, If any_RefundAdvanceCollect_f61fed</name>
   <tag></tag>
   <elementGuidId>40d32bda-605d-49c6-8b9a-cf9c86277bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='RefundAdvanceCollectionDlgForm:txtRefundNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d7a566fd-8e71-48be-8256-42080d53d5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RefundAdvanceCollectionDlgForm:txtRefundNote</value>
      <webElementGuid>b1ba3c6c-0dee-4487-83ce-354436837e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RefundAdvanceCollectionDlgForm:txtRefundNote</value>
      <webElementGuid>3c2cd75d-0e15-4901-ad36-e04b4ccb8fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4f7175d8-c365-4e99-a973-fefb9b52dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7b35c495-5435-43af-bd58-e962efcdb351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>d06b6fde-2e01-41a4-ac1f-f99976c63d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all ui-inputtextarea-resizable ui-state-hover ui-state-focus</value>
      <webElementGuid>7ad78f7f-120c-42c0-ad08-9a45a63ecfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8a8ad892-306a-4557-a6ca-c9e11fc88873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41b425b6-830b-4f1c-a657-4c830b4ced1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc6727ab-3392-4db7-9482-1db1b7b5f461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f03089e-1bca-4658-af94-cfc962d2aeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autosize-on</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c8b8d92-ba2b-40a6-aee8-31a32cdcd93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RefundAdvanceCollectionDlgForm:txtRefundNote&quot;)</value>
      <webElementGuid>edaa27d5-d8da-43b6-aea5-0ae40a42cc77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='RefundAdvanceCollectionDlgForm:txtRefundNote']</value>
      <webElementGuid>8fb3e5cf-7a05-4952-a6f4-3a04cf319189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='RefundAdvanceCollectionDlgForm:j_idt248']/tbody/tr[3]/td[2]/textarea</value>
      <webElementGuid>a2128ce8-4f85-40d5-b820-29339750944c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b4d0bffa-4961-44c6-82a2-eac5d17c6f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'RefundAdvanceCollectionDlgForm:txtRefundNote' and @name = 'RefundAdvanceCollectionDlgForm:txtRefundNote']</value>
      <webElementGuid>53bd34f9-af25-485a-89b4-9fd859136a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
