<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4</name>
   <tag></tag>
   <elementGuidId>c5fc153d-d44c-4ff9-90d3-87c65f2f2af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/table/tbody/tr/td[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-state-default.ui-state-highlight.ui-state-active.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f9d2a75-03cd-42de-89ab-93ca0164bad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-state-default ui-state-highlight ui-state-active ui-state-hover</value>
      <webElementGuid>d6fabb7a-163f-4f47-bdc9-a4992d5f54ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>720eded1-1ce0-4cf3-90c1-3bdd6e673596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b64bfb78-0d32-4e87-a193-f5ae37835087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/table[@class=&quot;ui-datepicker-calendar&quot;]/tbody[1]/tr[1]/td[@class=&quot;ui-datepicker-days-cell-over  ui-datepicker-current-day ui-datepicker-today&quot;]/a[@class=&quot;ui-state-default ui-state-highlight ui-state-active ui-state-hover&quot;]</value>
      <webElementGuid>11860bf3-b7b7-45a4-8dfa-bbaf5365d26b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/table/tbody/tr/td[6]/a</value>
      <webElementGuid>10186ada-01df-4de9-b097-52b0481e5179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'4')]</value>
      <webElementGuid>4e6dbbe3-8d6c-45dd-a282-fa76a66af652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::a[4]</value>
      <webElementGuid>9bd093dc-4ff2-48fe-b670-30dabfe7fba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::a[4]</value>
      <webElementGuid>97a6a00e-7959-4917-88a1-513ef119e820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[3]/preceding::a[27]</value>
      <webElementGuid>f0f8af0a-7f94-4812-9b18-ff1e7098d827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OP'])[2]/preceding::a[27]</value>
      <webElementGuid>103099bf-efd5-4d10-8628-4c91c861ae5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>259c6a05-9110-487b-8ccd-711cdef750c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[26]</value>
      <webElementGuid>09ce54d8-f0d0-40bd-9bcf-9c9b9cd71418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>67c22001-7295-433a-81e8-4bc890bd86c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '4' or . = '4')]</value>
      <webElementGuid>d9cae16f-4fda-4ced-ac97-02efeccda775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
